/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hp.supplier.jdbc;

import com.hp.supplier.dao.*;
import com.hp.supplier.factory.*;
import java.util.Date;
import com.hp.supplier.dto.*;
import com.hp.supplier.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class OpportunitiesDaoImpl extends AbstractDAO implements OpportunitiesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, supplier_id, unique_products, portfolio, recongnisation, key_words, date_creation, date_modification FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, supplier_id, unique_products, portfolio, recongnisation, key_words, date_creation, date_modification ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, supplier_id = ?, unique_products = ?, portfolio = ?, recongnisation = ?, key_words = ?, date_creation = ?, date_modification = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column supplier_id
	 */
	protected static final int COLUMN_SUPPLIER_ID = 2;

	/** 
	 * Index of column unique_products
	 */
	protected static final int COLUMN_UNIQUE_PRODUCTS = 3;

	/** 
	 * Index of column portfolio
	 */
	protected static final int COLUMN_PORTFOLIO = 4;

	/** 
	 * Index of column recongnisation
	 */
	protected static final int COLUMN_RECONGNISATION = 5;

	/** 
	 * Index of column key_words
	 */
	protected static final int COLUMN_KEY_WORDS = 6;

	/** 
	 * Index of column date_creation
	 */
	protected static final int COLUMN_DATE_CREATION = 7;

	/** 
	 * Index of column date_modification
	 */
	protected static final int COLUMN_DATE_MODIFICATION = 8;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 8;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the opportunities table.
	 */
	public OpportunitiesPk insert(Opportunities dto) throws OpportunitiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSupplierIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "supplier_id" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isUniqueProductsModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "unique_products" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPortfolioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "portfolio" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isRecongnisationModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "recongnisation" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isKeyWordsModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "key_words" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDateCreationModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "date_creation" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDateModificationModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "date_modification" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdModified()) {
				stmt.setInt( index++, dto.getId() );
			}
		
			if (dto.isSupplierIdModified()) {
				stmt.setInt( index++, dto.getSupplierId() );
			}
		
			if (dto.isUniqueProductsModified()) {
				stmt.setString( index++, dto.getUniqueProducts() );
			}
		
			if (dto.isPortfolioModified()) {
				stmt.setString( index++, dto.getPortfolio() );
			}
		
			if (dto.isRecongnisationModified()) {
				stmt.setString( index++, dto.getRecongnisation() );
			}
		
			if (dto.isKeyWordsModified()) {
				stmt.setString( index++, dto.getKeyWords() );
			}
		
			if (dto.isDateCreationModified()) {
				stmt.setTimestamp(index++, dto.getDateCreation()==null ? null : new java.sql.Timestamp( dto.getDateCreation().getTime() ) );
			}
		
			if (dto.isDateModificationModified()) {
				stmt.setTimestamp(index++, dto.getDateModification()==null ? null : new java.sql.Timestamp( dto.getDateModification().getTime() ) );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new OpportunitiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the opportunities table.
	 */
	public void update(OpportunitiesPk pk, Opportunities dto) throws OpportunitiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "id=?" );
				modified=true;
			}
		
			if (dto.isSupplierIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "supplier_id=?" );
				modified=true;
			}
		
			if (dto.isUniqueProductsModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "unique_products=?" );
				modified=true;
			}
		
			if (dto.isPortfolioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "portfolio=?" );
				modified=true;
			}
		
			if (dto.isRecongnisationModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "recongnisation=?" );
				modified=true;
			}
		
			if (dto.isKeyWordsModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "key_words=?" );
				modified=true;
			}
		
			if (dto.isDateCreationModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "date_creation=?" );
				modified=true;
			}
		
			if (dto.isDateModificationModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "date_modification=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE id=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdModified()) {
				stmt.setInt( index++, dto.getId() );
			}
		
			if (dto.isSupplierIdModified()) {
				stmt.setInt( index++, dto.getSupplierId() );
			}
		
			if (dto.isUniqueProductsModified()) {
				stmt.setString( index++, dto.getUniqueProducts() );
			}
		
			if (dto.isPortfolioModified()) {
				stmt.setString( index++, dto.getPortfolio() );
			}
		
			if (dto.isRecongnisationModified()) {
				stmt.setString( index++, dto.getRecongnisation() );
			}
		
			if (dto.isKeyWordsModified()) {
				stmt.setString( index++, dto.getKeyWords() );
			}
		
			if (dto.isDateCreationModified()) {
				stmt.setTimestamp(index++, dto.getDateCreation()==null ? null : new java.sql.Timestamp( dto.getDateCreation().getTime() ) );
			}
		
			if (dto.isDateModificationModified()) {
				stmt.setTimestamp(index++, dto.getDateModification()==null ? null : new java.sql.Timestamp( dto.getDateModification().getTime() ) );
			}
		
			stmt.setInt( index++, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new OpportunitiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the opportunities table.
	 */
	public void delete(OpportunitiesPk pk) throws OpportunitiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new OpportunitiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the opportunities table that matches the specified primary-key value.
	 */
	public Opportunities findByPrimaryKey(OpportunitiesPk pk) throws OpportunitiesDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'id = :id'.
	 */
	public Opportunities findByPrimaryKey(int id) throws OpportunitiesDaoException
	{
		Opportunities ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria ''.
	 */
	public Opportunities[] findAll() throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'supplier_id = :supplierId'.
	 */
	public Opportunities[] findBySubmissionForm(int supplierId) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE supplier_id = ?", new Object[] {  new Integer(supplierId) } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'id = :id'.
	 */
	public Opportunities[] findWhereIdEquals(int id) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'supplier_id = :supplierId'.
	 */
	public Opportunities[] findWhereSupplierIdEquals(int supplierId) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE supplier_id = ? ORDER BY supplier_id", new Object[] {  new Integer(supplierId) } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'unique_products = :uniqueProducts'.
	 */
	public Opportunities[] findWhereUniqueProductsEquals(String uniqueProducts) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE unique_products = ? ORDER BY unique_products", new Object[] { uniqueProducts } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'portfolio = :portfolio'.
	 */
	public Opportunities[] findWherePortfolioEquals(String portfolio) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE portfolio = ? ORDER BY portfolio", new Object[] { portfolio } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'recongnisation = :recongnisation'.
	 */
	public Opportunities[] findWhereRecongnisationEquals(String recongnisation) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE recongnisation = ? ORDER BY recongnisation", new Object[] { recongnisation } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'key_words = :keyWords'.
	 */
	public Opportunities[] findWhereKeyWordsEquals(String keyWords) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE key_words = ? ORDER BY key_words", new Object[] { keyWords } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'date_creation = :dateCreation'.
	 */
	public Opportunities[] findWhereDateCreationEquals(Date dateCreation) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE date_creation = ? ORDER BY date_creation", new Object[] { dateCreation==null ? null : new java.sql.Timestamp( dateCreation.getTime() ) } );
	}

	/** 
	 * Returns all rows from the opportunities table that match the criteria 'date_modification = :dateModification'.
	 */
	public Opportunities[] findWhereDateModificationEquals(Date dateModification) throws OpportunitiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE date_modification = ? ORDER BY date_modification", new Object[] { dateModification==null ? null : new java.sql.Timestamp( dateModification.getTime() ) } );
	}

	/**
	 * Method 'OpportunitiesDaoImpl'
	 * 
	 */
	public OpportunitiesDaoImpl()
	{
	}

	/**
	 * Method 'OpportunitiesDaoImpl'
	 * 
	 * @param userConn
	 */
	public OpportunitiesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "supplierdb.opportunities";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Opportunities fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Opportunities dto = new Opportunities();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Opportunities[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Opportunities dto = new Opportunities();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Opportunities ret[] = new Opportunities[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Opportunities dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setSupplierId( rs.getInt( COLUMN_SUPPLIER_ID ) );
		dto.setUniqueProducts( rs.getString( COLUMN_UNIQUE_PRODUCTS ) );
		dto.setPortfolio( rs.getString( COLUMN_PORTFOLIO ) );
		dto.setRecongnisation( rs.getString( COLUMN_RECONGNISATION ) );
		dto.setKeyWords( rs.getString( COLUMN_KEY_WORDS ) );
		dto.setDateCreation( rs.getTimestamp(COLUMN_DATE_CREATION ) );
		dto.setDateModification( rs.getTimestamp(COLUMN_DATE_MODIFICATION ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Opportunities dto)
	{
		dto.setIdModified( false );
		dto.setSupplierIdModified( false );
		dto.setUniqueProductsModified( false );
		dto.setPortfolioModified( false );
		dto.setRecongnisationModified( false );
		dto.setKeyWordsModified( false );
		dto.setDateCreationModified( false );
		dto.setDateModificationModified( false );
	}

	/** 
	 * Returns all rows from the opportunities table that match the specified arbitrary SQL statement
	 */
	public Opportunities[] findByDynamicSelect(String sql, Object[] sqlParams) throws OpportunitiesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new OpportunitiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the opportunities table that match the specified arbitrary SQL statement
	 */
	public Opportunities[] findByDynamicWhere(String sql, Object[] sqlParams) throws OpportunitiesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new OpportunitiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
