/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hp.supplier.dto;

import com.hp.supplier.dao.*;
import com.hp.supplier.factory.*;
import com.hp.supplier.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Contactsreferences implements Serializable
{
	/** 
	 * This attribute maps to the column id in the contactsreferences table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column supplier_id in the contactsreferences table.
	 */
	protected int supplierId;

	/** 
	 * This attribute represents whether the attribute supplierId has been modified since being read from the database.
	 */
	protected boolean supplierIdModified = false;

	/** 
	 * This attribute maps to the column is_HP_trader in the contactsreferences table.
	 */
	protected String isHpTrader;

	/** 
	 * This attribute represents whether the attribute isHpTrader has been modified since being read from the database.
	 */
	protected boolean isHpTraderModified = false;

	/** 
	 * This attribute maps to the column contract_title in the contactsreferences table.
	 */
	protected String contractTitle;

	/** 
	 * This attribute represents whether the attribute contractTitle has been modified since being read from the database.
	 */
	protected boolean contractTitleModified = false;

	/** 
	 * This attribute maps to the column contract_ref in the contactsreferences table.
	 */
	protected String contractRef;

	/** 
	 * This attribute represents whether the attribute contractRef has been modified since being read from the database.
	 */
	protected boolean contractRefModified = false;

	/** 
	 * This attribute maps to the column expiry_date in the contactsreferences table.
	 */
	protected String expiryDate;

	/** 
	 * This attribute represents whether the attribute expiryDate has been modified since being read from the database.
	 */
	protected boolean expiryDateModified = false;

	/** 
	 * This attribute maps to the column hp_contract_mgr in the contactsreferences table.
	 */
	protected String hpContractMgr;

	/** 
	 * This attribute represents whether the attribute hpContractMgr has been modified since being read from the database.
	 */
	protected boolean hpContractMgrModified = false;

	/** 
	 * This attribute maps to the column div_name_1 in the contactsreferences table.
	 */
	protected String divName1;

	/** 
	 * This attribute represents whether the attribute divName1 has been modified since being read from the database.
	 */
	protected boolean divName1Modified = false;

	/** 
	 * This attribute maps to the column contact_name_1 in the contactsreferences table.
	 */
	protected String contactName1;

	/** 
	 * This attribute represents whether the attribute contactName1 has been modified since being read from the database.
	 */
	protected boolean contactName1Modified = false;

	/** 
	 * This attribute maps to the column site_location_1 in the contactsreferences table.
	 */
	protected String siteLocation1;

	/** 
	 * This attribute represents whether the attribute siteLocation1 has been modified since being read from the database.
	 */
	protected boolean siteLocation1Modified = false;

	/** 
	 * This attribute maps to the column last_meeting_date_1 in the contactsreferences table.
	 */
	protected Date lastMeetingDate1;

	/** 
	 * This attribute represents whether the attribute lastMeetingDate1 has been modified since being read from the database.
	 */
	protected boolean lastMeetingDate1Modified = false;

	/** 
	 * This attribute maps to the column approx_service_period_1 in the contactsreferences table.
	 */
	protected String approxServicePeriod1;

	/** 
	 * This attribute represents whether the attribute approxServicePeriod1 has been modified since being read from the database.
	 */
	protected boolean approxServicePeriod1Modified = false;

	/** 
	 * This attribute maps to the column div_name_2 in the contactsreferences table.
	 */
	protected String divName2;

	/** 
	 * This attribute represents whether the attribute divName2 has been modified since being read from the database.
	 */
	protected boolean divName2Modified = false;

	/** 
	 * This attribute maps to the column hp_contact_name_2 in the contactsreferences table.
	 */
	protected String hpContactName2;

	/** 
	 * This attribute represents whether the attribute hpContactName2 has been modified since being read from the database.
	 */
	protected boolean hpContactName2Modified = false;

	/** 
	 * This attribute maps to the column site_location_2 in the contactsreferences table.
	 */
	protected String siteLocation2;

	/** 
	 * This attribute represents whether the attribute siteLocation2 has been modified since being read from the database.
	 */
	protected boolean siteLocation2Modified = false;

	/** 
	 * This attribute maps to the column last_meeting_date_2 in the contactsreferences table.
	 */
	protected Date lastMeetingDate2;

	/** 
	 * This attribute represents whether the attribute lastMeetingDate2 has been modified since being read from the database.
	 */
	protected boolean lastMeetingDate2Modified = false;

	/** 
	 * This attribute maps to the column approx_service_period_2 in the contactsreferences table.
	 */
	protected String approxServicePeriod2;

	/** 
	 * This attribute represents whether the attribute approxServicePeriod2 has been modified since being read from the database.
	 */
	protected boolean approxServicePeriod2Modified = false;

	/** 
	 * This attribute maps to the column div_name_3 in the contactsreferences table.
	 */
	protected String divName3;

	/** 
	 * This attribute represents whether the attribute divName3 has been modified since being read from the database.
	 */
	protected boolean divName3Modified = false;

	/** 
	 * This attribute maps to the column hp_contact_name_3 in the contactsreferences table.
	 */
	protected String hpContactName3;

	/** 
	 * This attribute represents whether the attribute hpContactName3 has been modified since being read from the database.
	 */
	protected boolean hpContactName3Modified = false;

	/** 
	 * This attribute maps to the column site_location_3 in the contactsreferences table.
	 */
	protected String siteLocation3;

	/** 
	 * This attribute represents whether the attribute siteLocation3 has been modified since being read from the database.
	 */
	protected boolean siteLocation3Modified = false;

	/** 
	 * This attribute maps to the column last_meeting_date_3 in the contactsreferences table.
	 */
	protected Date lastMeetingDate3;

	/** 
	 * This attribute represents whether the attribute lastMeetingDate3 has been modified since being read from the database.
	 */
	protected boolean lastMeetingDate3Modified = false;

	/** 
	 * This attribute maps to the column approx_service_period_3 in the contactsreferences table.
	 */
	protected String approxServicePeriod3;

	/** 
	 * This attribute represents whether the attribute approxServicePeriod3 has been modified since being read from the database.
	 */
	protected boolean approxServicePeriod3Modified = false;

	/** 
	 * This attribute maps to the column organization_1 in the contactsreferences table.
	 */
	protected String organization1;

	/** 
	 * This attribute represents whether the attribute organization1 has been modified since being read from the database.
	 */
	protected boolean organization1Modified = false;

	/** 
	 * This attribute maps to the column hp_contact_name_1 in the contactsreferences table.
	 */
	protected String hpContactName1;

	/** 
	 * This attribute represents whether the attribute hpContactName1 has been modified since being read from the database.
	 */
	protected boolean hpContactName1Modified = false;

	/** 
	 * This attribute maps to the column contact_title_1 in the contactsreferences table.
	 */
	protected String contactTitle1;

	/** 
	 * This attribute represents whether the attribute contactTitle1 has been modified since being read from the database.
	 */
	protected boolean contactTitle1Modified = false;

	/** 
	 * This attribute maps to the column email_address_1 in the contactsreferences table.
	 */
	protected String emailAddress1;

	/** 
	 * This attribute represents whether the attribute emailAddress1 has been modified since being read from the database.
	 */
	protected boolean emailAddress1Modified = false;

	/** 
	 * This attribute maps to the column organization_2 in the contactsreferences table.
	 */
	protected String organization2;

	/** 
	 * This attribute represents whether the attribute organization2 has been modified since being read from the database.
	 */
	protected boolean organization2Modified = false;

	/** 
	 * This attribute maps to the column contact_name_2 in the contactsreferences table.
	 */
	protected String contactName2;

	/** 
	 * This attribute represents whether the attribute contactName2 has been modified since being read from the database.
	 */
	protected boolean contactName2Modified = false;

	/** 
	 * This attribute maps to the column contact_title_2 in the contactsreferences table.
	 */
	protected String contactTitle2;

	/** 
	 * This attribute represents whether the attribute contactTitle2 has been modified since being read from the database.
	 */
	protected boolean contactTitle2Modified = false;

	/** 
	 * This attribute maps to the column email_address_2 in the contactsreferences table.
	 */
	protected String emailAddress2;

	/** 
	 * This attribute represents whether the attribute emailAddress2 has been modified since being read from the database.
	 */
	protected boolean emailAddress2Modified = false;

	/** 
	 * This attribute maps to the column organization_3 in the contactsreferences table.
	 */
	protected String organization3;

	/** 
	 * This attribute represents whether the attribute organization3 has been modified since being read from the database.
	 */
	protected boolean organization3Modified = false;

	/** 
	 * This attribute maps to the column contact_name_3 in the contactsreferences table.
	 */
	protected String contactName3;

	/** 
	 * This attribute represents whether the attribute contactName3 has been modified since being read from the database.
	 */
	protected boolean contactName3Modified = false;

	/** 
	 * This attribute maps to the column contact_title_3 in the contactsreferences table.
	 */
	protected String contactTitle3;

	/** 
	 * This attribute represents whether the attribute contactTitle3 has been modified since being read from the database.
	 */
	protected boolean contactTitle3Modified = false;

	/** 
	 * This attribute maps to the column email_address_3 in the contactsreferences table.
	 */
	protected String emailAddress3;

	/** 
	 * This attribute represents whether the attribute emailAddress3 has been modified since being read from the database.
	 */
	protected boolean emailAddress3Modified = false;

	/** 
	 * This attribute maps to the column date_created in the contactsreferences table.
	 */
	protected Date dateCreated;

	/** 
	 * This attribute represents whether the attribute dateCreated has been modified since being read from the database.
	 */
	protected boolean dateCreatedModified = false;

	/** 
	 * This attribute maps to the column date_modified in the contactsreferences table.
	 */
	protected Date dateModified;

	/** 
	 * This attribute represents whether the attribute dateModified has been modified since being read from the database.
	 */
	protected boolean dateModifiedModified = false;

	/**
	 * Method 'Contactsreferences'
	 * 
	 */
	public Contactsreferences()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getSupplierId'
	 * 
	 * @return int
	 */
	public int getSupplierId()
	{
		return supplierId;
	}

	/**
	 * Method 'setSupplierId'
	 * 
	 * @param supplierId
	 */
	public void setSupplierId(int supplierId)
	{
		this.supplierId = supplierId;
		this.supplierIdModified = true;
	}

	/** 
	 * Sets the value of supplierIdModified
	 */
	public void setSupplierIdModified(boolean supplierIdModified)
	{
		this.supplierIdModified = supplierIdModified;
	}

	/** 
	 * Gets the value of supplierIdModified
	 */
	public boolean isSupplierIdModified()
	{
		return supplierIdModified;
	}

	/**
	 * Method 'getIsHpTrader'
	 * 
	 * @return String
	 */
	public String getIsHpTrader()
	{
		return isHpTrader;
	}

	/**
	 * Method 'setIsHpTrader'
	 * 
	 * @param isHpTrader
	 */
	public void setIsHpTrader(String isHpTrader)
	{
		this.isHpTrader = isHpTrader;
		this.isHpTraderModified = true;
	}

	/** 
	 * Sets the value of isHpTraderModified
	 */
	public void setIsHpTraderModified(boolean isHpTraderModified)
	{
		this.isHpTraderModified = isHpTraderModified;
	}

	/** 
	 * Gets the value of isHpTraderModified
	 */
	public boolean isIsHpTraderModified()
	{
		return isHpTraderModified;
	}

	/**
	 * Method 'getContractTitle'
	 * 
	 * @return String
	 */
	public String getContractTitle()
	{
		return contractTitle;
	}

	/**
	 * Method 'setContractTitle'
	 * 
	 * @param contractTitle
	 */
	public void setContractTitle(String contractTitle)
	{
		this.contractTitle = contractTitle;
		this.contractTitleModified = true;
	}

	/** 
	 * Sets the value of contractTitleModified
	 */
	public void setContractTitleModified(boolean contractTitleModified)
	{
		this.contractTitleModified = contractTitleModified;
	}

	/** 
	 * Gets the value of contractTitleModified
	 */
	public boolean isContractTitleModified()
	{
		return contractTitleModified;
	}

	/**
	 * Method 'getContractRef'
	 * 
	 * @return String
	 */
	public String getContractRef()
	{
		return contractRef;
	}

	/**
	 * Method 'setContractRef'
	 * 
	 * @param contractRef
	 */
	public void setContractRef(String contractRef)
	{
		this.contractRef = contractRef;
		this.contractRefModified = true;
	}

	/** 
	 * Sets the value of contractRefModified
	 */
	public void setContractRefModified(boolean contractRefModified)
	{
		this.contractRefModified = contractRefModified;
	}

	/** 
	 * Gets the value of contractRefModified
	 */
	public boolean isContractRefModified()
	{
		return contractRefModified;
	}

	/**
	 * Method 'getExpiryDate'
	 * 
	 * @return String
	 */
	public String getExpiryDate()
	{
		return expiryDate;
	}

	/**
	 * Method 'setExpiryDate'
	 * 
	 * @param expiryDate
	 */
	public void setExpiryDate(String expiryDate)
	{
		this.expiryDate = expiryDate;
		this.expiryDateModified = true;
	}

	/** 
	 * Sets the value of expiryDateModified
	 */
	public void setExpiryDateModified(boolean expiryDateModified)
	{
		this.expiryDateModified = expiryDateModified;
	}

	/** 
	 * Gets the value of expiryDateModified
	 */
	public boolean isExpiryDateModified()
	{
		return expiryDateModified;
	}

	/**
	 * Method 'getHpContractMgr'
	 * 
	 * @return String
	 */
	public String getHpContractMgr()
	{
		return hpContractMgr;
	}

	/**
	 * Method 'setHpContractMgr'
	 * 
	 * @param hpContractMgr
	 */
	public void setHpContractMgr(String hpContractMgr)
	{
		this.hpContractMgr = hpContractMgr;
		this.hpContractMgrModified = true;
	}

	/** 
	 * Sets the value of hpContractMgrModified
	 */
	public void setHpContractMgrModified(boolean hpContractMgrModified)
	{
		this.hpContractMgrModified = hpContractMgrModified;
	}

	/** 
	 * Gets the value of hpContractMgrModified
	 */
	public boolean isHpContractMgrModified()
	{
		return hpContractMgrModified;
	}

	/**
	 * Method 'getDivName1'
	 * 
	 * @return String
	 */
	public String getDivName1()
	{
		return divName1;
	}

	/**
	 * Method 'setDivName1'
	 * 
	 * @param divName1
	 */
	public void setDivName1(String divName1)
	{
		this.divName1 = divName1;
		this.divName1Modified = true;
	}

	/** 
	 * Sets the value of divName1Modified
	 */
	public void setDivName1Modified(boolean divName1Modified)
	{
		this.divName1Modified = divName1Modified;
	}

	/** 
	 * Gets the value of divName1Modified
	 */
	public boolean isDivName1Modified()
	{
		return divName1Modified;
	}

	/**
	 * Method 'getContactName1'
	 * 
	 * @return String
	 */
	public String getContactName1()
	{
		return contactName1;
	}

	/**
	 * Method 'setContactName1'
	 * 
	 * @param contactName1
	 */
	public void setContactName1(String contactName1)
	{
		this.contactName1 = contactName1;
		this.contactName1Modified = true;
	}

	/** 
	 * Sets the value of contactName1Modified
	 */
	public void setContactName1Modified(boolean contactName1Modified)
	{
		this.contactName1Modified = contactName1Modified;
	}

	/** 
	 * Gets the value of contactName1Modified
	 */
	public boolean isContactName1Modified()
	{
		return contactName1Modified;
	}

	/**
	 * Method 'getSiteLocation1'
	 * 
	 * @return String
	 */
	public String getSiteLocation1()
	{
		return siteLocation1;
	}

	/**
	 * Method 'setSiteLocation1'
	 * 
	 * @param siteLocation1
	 */
	public void setSiteLocation1(String siteLocation1)
	{
		this.siteLocation1 = siteLocation1;
		this.siteLocation1Modified = true;
	}

	/** 
	 * Sets the value of siteLocation1Modified
	 */
	public void setSiteLocation1Modified(boolean siteLocation1Modified)
	{
		this.siteLocation1Modified = siteLocation1Modified;
	}

	/** 
	 * Gets the value of siteLocation1Modified
	 */
	public boolean isSiteLocation1Modified()
	{
		return siteLocation1Modified;
	}

	/**
	 * Method 'getLastMeetingDate1'
	 * 
	 * @return Date
	 */
	public Date getLastMeetingDate1()
	{
		return lastMeetingDate1;
	}

	/**
	 * Method 'setLastMeetingDate1'
	 * 
	 * @param lastMeetingDate1
	 */
	public void setLastMeetingDate1(Date lastMeetingDate1)
	{
		this.lastMeetingDate1 = lastMeetingDate1;
		this.lastMeetingDate1Modified = true;
	}

	/** 
	 * Sets the value of lastMeetingDate1Modified
	 */
	public void setLastMeetingDate1Modified(boolean lastMeetingDate1Modified)
	{
		this.lastMeetingDate1Modified = lastMeetingDate1Modified;
	}

	/** 
	 * Gets the value of lastMeetingDate1Modified
	 */
	public boolean isLastMeetingDate1Modified()
	{
		return lastMeetingDate1Modified;
	}

	/**
	 * Method 'getApproxServicePeriod1'
	 * 
	 * @return String
	 */
	public String getApproxServicePeriod1()
	{
		return approxServicePeriod1;
	}

	/**
	 * Method 'setApproxServicePeriod1'
	 * 
	 * @param approxServicePeriod1
	 */
	public void setApproxServicePeriod1(String approxServicePeriod1)
	{
		this.approxServicePeriod1 = approxServicePeriod1;
		this.approxServicePeriod1Modified = true;
	}

	/** 
	 * Sets the value of approxServicePeriod1Modified
	 */
	public void setApproxServicePeriod1Modified(boolean approxServicePeriod1Modified)
	{
		this.approxServicePeriod1Modified = approxServicePeriod1Modified;
	}

	/** 
	 * Gets the value of approxServicePeriod1Modified
	 */
	public boolean isApproxServicePeriod1Modified()
	{
		return approxServicePeriod1Modified;
	}

	/**
	 * Method 'getDivName2'
	 * 
	 * @return String
	 */
	public String getDivName2()
	{
		return divName2;
	}

	/**
	 * Method 'setDivName2'
	 * 
	 * @param divName2
	 */
	public void setDivName2(String divName2)
	{
		this.divName2 = divName2;
		this.divName2Modified = true;
	}

	/** 
	 * Sets the value of divName2Modified
	 */
	public void setDivName2Modified(boolean divName2Modified)
	{
		this.divName2Modified = divName2Modified;
	}

	/** 
	 * Gets the value of divName2Modified
	 */
	public boolean isDivName2Modified()
	{
		return divName2Modified;
	}

	/**
	 * Method 'getHpContactName2'
	 * 
	 * @return String
	 */
	public String getHpContactName2()
	{
		return hpContactName2;
	}

	/**
	 * Method 'setHpContactName2'
	 * 
	 * @param hpContactName2
	 */
	public void setHpContactName2(String hpContactName2)
	{
		this.hpContactName2 = hpContactName2;
		this.hpContactName2Modified = true;
	}

	/** 
	 * Sets the value of hpContactName2Modified
	 */
	public void setHpContactName2Modified(boolean hpContactName2Modified)
	{
		this.hpContactName2Modified = hpContactName2Modified;
	}

	/** 
	 * Gets the value of hpContactName2Modified
	 */
	public boolean isHpContactName2Modified()
	{
		return hpContactName2Modified;
	}

	/**
	 * Method 'getSiteLocation2'
	 * 
	 * @return String
	 */
	public String getSiteLocation2()
	{
		return siteLocation2;
	}

	/**
	 * Method 'setSiteLocation2'
	 * 
	 * @param siteLocation2
	 */
	public void setSiteLocation2(String siteLocation2)
	{
		this.siteLocation2 = siteLocation2;
		this.siteLocation2Modified = true;
	}

	/** 
	 * Sets the value of siteLocation2Modified
	 */
	public void setSiteLocation2Modified(boolean siteLocation2Modified)
	{
		this.siteLocation2Modified = siteLocation2Modified;
	}

	/** 
	 * Gets the value of siteLocation2Modified
	 */
	public boolean isSiteLocation2Modified()
	{
		return siteLocation2Modified;
	}

	/**
	 * Method 'getLastMeetingDate2'
	 * 
	 * @return Date
	 */
	public Date getLastMeetingDate2()
	{
		return lastMeetingDate2;
	}

	/**
	 * Method 'setLastMeetingDate2'
	 * 
	 * @param lastMeetingDate2
	 */
	public void setLastMeetingDate2(Date lastMeetingDate2)
	{
		this.lastMeetingDate2 = lastMeetingDate2;
		this.lastMeetingDate2Modified = true;
	}

	/** 
	 * Sets the value of lastMeetingDate2Modified
	 */
	public void setLastMeetingDate2Modified(boolean lastMeetingDate2Modified)
	{
		this.lastMeetingDate2Modified = lastMeetingDate2Modified;
	}

	/** 
	 * Gets the value of lastMeetingDate2Modified
	 */
	public boolean isLastMeetingDate2Modified()
	{
		return lastMeetingDate2Modified;
	}

	/**
	 * Method 'getApproxServicePeriod2'
	 * 
	 * @return String
	 */
	public String getApproxServicePeriod2()
	{
		return approxServicePeriod2;
	}

	/**
	 * Method 'setApproxServicePeriod2'
	 * 
	 * @param approxServicePeriod2
	 */
	public void setApproxServicePeriod2(String approxServicePeriod2)
	{
		this.approxServicePeriod2 = approxServicePeriod2;
		this.approxServicePeriod2Modified = true;
	}

	/** 
	 * Sets the value of approxServicePeriod2Modified
	 */
	public void setApproxServicePeriod2Modified(boolean approxServicePeriod2Modified)
	{
		this.approxServicePeriod2Modified = approxServicePeriod2Modified;
	}

	/** 
	 * Gets the value of approxServicePeriod2Modified
	 */
	public boolean isApproxServicePeriod2Modified()
	{
		return approxServicePeriod2Modified;
	}

	/**
	 * Method 'getDivName3'
	 * 
	 * @return String
	 */
	public String getDivName3()
	{
		return divName3;
	}

	/**
	 * Method 'setDivName3'
	 * 
	 * @param divName3
	 */
	public void setDivName3(String divName3)
	{
		this.divName3 = divName3;
		this.divName3Modified = true;
	}

	/** 
	 * Sets the value of divName3Modified
	 */
	public void setDivName3Modified(boolean divName3Modified)
	{
		this.divName3Modified = divName3Modified;
	}

	/** 
	 * Gets the value of divName3Modified
	 */
	public boolean isDivName3Modified()
	{
		return divName3Modified;
	}

	/**
	 * Method 'getHpContactName3'
	 * 
	 * @return String
	 */
	public String getHpContactName3()
	{
		return hpContactName3;
	}

	/**
	 * Method 'setHpContactName3'
	 * 
	 * @param hpContactName3
	 */
	public void setHpContactName3(String hpContactName3)
	{
		this.hpContactName3 = hpContactName3;
		this.hpContactName3Modified = true;
	}

	/** 
	 * Sets the value of hpContactName3Modified
	 */
	public void setHpContactName3Modified(boolean hpContactName3Modified)
	{
		this.hpContactName3Modified = hpContactName3Modified;
	}

	/** 
	 * Gets the value of hpContactName3Modified
	 */
	public boolean isHpContactName3Modified()
	{
		return hpContactName3Modified;
	}

	/**
	 * Method 'getSiteLocation3'
	 * 
	 * @return String
	 */
	public String getSiteLocation3()
	{
		return siteLocation3;
	}

	/**
	 * Method 'setSiteLocation3'
	 * 
	 * @param siteLocation3
	 */
	public void setSiteLocation3(String siteLocation3)
	{
		this.siteLocation3 = siteLocation3;
		this.siteLocation3Modified = true;
	}

	/** 
	 * Sets the value of siteLocation3Modified
	 */
	public void setSiteLocation3Modified(boolean siteLocation3Modified)
	{
		this.siteLocation3Modified = siteLocation3Modified;
	}

	/** 
	 * Gets the value of siteLocation3Modified
	 */
	public boolean isSiteLocation3Modified()
	{
		return siteLocation3Modified;
	}

	/**
	 * Method 'getLastMeetingDate3'
	 * 
	 * @return Date
	 */
	public Date getLastMeetingDate3()
	{
		return lastMeetingDate3;
	}

	/**
	 * Method 'setLastMeetingDate3'
	 * 
	 * @param lastMeetingDate3
	 */
	public void setLastMeetingDate3(Date lastMeetingDate3)
	{
		this.lastMeetingDate3 = lastMeetingDate3;
		this.lastMeetingDate3Modified = true;
	}

	/** 
	 * Sets the value of lastMeetingDate3Modified
	 */
	public void setLastMeetingDate3Modified(boolean lastMeetingDate3Modified)
	{
		this.lastMeetingDate3Modified = lastMeetingDate3Modified;
	}

	/** 
	 * Gets the value of lastMeetingDate3Modified
	 */
	public boolean isLastMeetingDate3Modified()
	{
		return lastMeetingDate3Modified;
	}

	/**
	 * Method 'getApproxServicePeriod3'
	 * 
	 * @return String
	 */
	public String getApproxServicePeriod3()
	{
		return approxServicePeriod3;
	}

	/**
	 * Method 'setApproxServicePeriod3'
	 * 
	 * @param approxServicePeriod3
	 */
	public void setApproxServicePeriod3(String approxServicePeriod3)
	{
		this.approxServicePeriod3 = approxServicePeriod3;
		this.approxServicePeriod3Modified = true;
	}

	/** 
	 * Sets the value of approxServicePeriod3Modified
	 */
	public void setApproxServicePeriod3Modified(boolean approxServicePeriod3Modified)
	{
		this.approxServicePeriod3Modified = approxServicePeriod3Modified;
	}

	/** 
	 * Gets the value of approxServicePeriod3Modified
	 */
	public boolean isApproxServicePeriod3Modified()
	{
		return approxServicePeriod3Modified;
	}

	/**
	 * Method 'getOrganization1'
	 * 
	 * @return String
	 */
	public String getOrganization1()
	{
		return organization1;
	}

	/**
	 * Method 'setOrganization1'
	 * 
	 * @param organization1
	 */
	public void setOrganization1(String organization1)
	{
		this.organization1 = organization1;
		this.organization1Modified = true;
	}

	/** 
	 * Sets the value of organization1Modified
	 */
	public void setOrganization1Modified(boolean organization1Modified)
	{
		this.organization1Modified = organization1Modified;
	}

	/** 
	 * Gets the value of organization1Modified
	 */
	public boolean isOrganization1Modified()
	{
		return organization1Modified;
	}

	/**
	 * Method 'getHpContactName1'
	 * 
	 * @return String
	 */
	public String getHpContactName1()
	{
		return hpContactName1;
	}

	/**
	 * Method 'setHpContactName1'
	 * 
	 * @param hpContactName1
	 */
	public void setHpContactName1(String hpContactName1)
	{
		this.hpContactName1 = hpContactName1;
		this.hpContactName1Modified = true;
	}

	/** 
	 * Sets the value of hpContactName1Modified
	 */
	public void setHpContactName1Modified(boolean hpContactName1Modified)
	{
		this.hpContactName1Modified = hpContactName1Modified;
	}

	/** 
	 * Gets the value of hpContactName1Modified
	 */
	public boolean isHpContactName1Modified()
	{
		return hpContactName1Modified;
	}

	/**
	 * Method 'getContactTitle1'
	 * 
	 * @return String
	 */
	public String getContactTitle1()
	{
		return contactTitle1;
	}

	/**
	 * Method 'setContactTitle1'
	 * 
	 * @param contactTitle1
	 */
	public void setContactTitle1(String contactTitle1)
	{
		this.contactTitle1 = contactTitle1;
		this.contactTitle1Modified = true;
	}

	/** 
	 * Sets the value of contactTitle1Modified
	 */
	public void setContactTitle1Modified(boolean contactTitle1Modified)
	{
		this.contactTitle1Modified = contactTitle1Modified;
	}

	/** 
	 * Gets the value of contactTitle1Modified
	 */
	public boolean isContactTitle1Modified()
	{
		return contactTitle1Modified;
	}

	/**
	 * Method 'getEmailAddress1'
	 * 
	 * @return String
	 */
	public String getEmailAddress1()
	{
		return emailAddress1;
	}

	/**
	 * Method 'setEmailAddress1'
	 * 
	 * @param emailAddress1
	 */
	public void setEmailAddress1(String emailAddress1)
	{
		this.emailAddress1 = emailAddress1;
		this.emailAddress1Modified = true;
	}

	/** 
	 * Sets the value of emailAddress1Modified
	 */
	public void setEmailAddress1Modified(boolean emailAddress1Modified)
	{
		this.emailAddress1Modified = emailAddress1Modified;
	}

	/** 
	 * Gets the value of emailAddress1Modified
	 */
	public boolean isEmailAddress1Modified()
	{
		return emailAddress1Modified;
	}

	/**
	 * Method 'getOrganization2'
	 * 
	 * @return String
	 */
	public String getOrganization2()
	{
		return organization2;
	}

	/**
	 * Method 'setOrganization2'
	 * 
	 * @param organization2
	 */
	public void setOrganization2(String organization2)
	{
		this.organization2 = organization2;
		this.organization2Modified = true;
	}

	/** 
	 * Sets the value of organization2Modified
	 */
	public void setOrganization2Modified(boolean organization2Modified)
	{
		this.organization2Modified = organization2Modified;
	}

	/** 
	 * Gets the value of organization2Modified
	 */
	public boolean isOrganization2Modified()
	{
		return organization2Modified;
	}

	/**
	 * Method 'getContactName2'
	 * 
	 * @return String
	 */
	public String getContactName2()
	{
		return contactName2;
	}

	/**
	 * Method 'setContactName2'
	 * 
	 * @param contactName2
	 */
	public void setContactName2(String contactName2)
	{
		this.contactName2 = contactName2;
		this.contactName2Modified = true;
	}

	/** 
	 * Sets the value of contactName2Modified
	 */
	public void setContactName2Modified(boolean contactName2Modified)
	{
		this.contactName2Modified = contactName2Modified;
	}

	/** 
	 * Gets the value of contactName2Modified
	 */
	public boolean isContactName2Modified()
	{
		return contactName2Modified;
	}

	/**
	 * Method 'getContactTitle2'
	 * 
	 * @return String
	 */
	public String getContactTitle2()
	{
		return contactTitle2;
	}

	/**
	 * Method 'setContactTitle2'
	 * 
	 * @param contactTitle2
	 */
	public void setContactTitle2(String contactTitle2)
	{
		this.contactTitle2 = contactTitle2;
		this.contactTitle2Modified = true;
	}

	/** 
	 * Sets the value of contactTitle2Modified
	 */
	public void setContactTitle2Modified(boolean contactTitle2Modified)
	{
		this.contactTitle2Modified = contactTitle2Modified;
	}

	/** 
	 * Gets the value of contactTitle2Modified
	 */
	public boolean isContactTitle2Modified()
	{
		return contactTitle2Modified;
	}

	/**
	 * Method 'getEmailAddress2'
	 * 
	 * @return String
	 */
	public String getEmailAddress2()
	{
		return emailAddress2;
	}

	/**
	 * Method 'setEmailAddress2'
	 * 
	 * @param emailAddress2
	 */
	public void setEmailAddress2(String emailAddress2)
	{
		this.emailAddress2 = emailAddress2;
		this.emailAddress2Modified = true;
	}

	/** 
	 * Sets the value of emailAddress2Modified
	 */
	public void setEmailAddress2Modified(boolean emailAddress2Modified)
	{
		this.emailAddress2Modified = emailAddress2Modified;
	}

	/** 
	 * Gets the value of emailAddress2Modified
	 */
	public boolean isEmailAddress2Modified()
	{
		return emailAddress2Modified;
	}

	/**
	 * Method 'getOrganization3'
	 * 
	 * @return String
	 */
	public String getOrganization3()
	{
		return organization3;
	}

	/**
	 * Method 'setOrganization3'
	 * 
	 * @param organization3
	 */
	public void setOrganization3(String organization3)
	{
		this.organization3 = organization3;
		this.organization3Modified = true;
	}

	/** 
	 * Sets the value of organization3Modified
	 */
	public void setOrganization3Modified(boolean organization3Modified)
	{
		this.organization3Modified = organization3Modified;
	}

	/** 
	 * Gets the value of organization3Modified
	 */
	public boolean isOrganization3Modified()
	{
		return organization3Modified;
	}

	/**
	 * Method 'getContactName3'
	 * 
	 * @return String
	 */
	public String getContactName3()
	{
		return contactName3;
	}

	/**
	 * Method 'setContactName3'
	 * 
	 * @param contactName3
	 */
	public void setContactName3(String contactName3)
	{
		this.contactName3 = contactName3;
		this.contactName3Modified = true;
	}

	/** 
	 * Sets the value of contactName3Modified
	 */
	public void setContactName3Modified(boolean contactName3Modified)
	{
		this.contactName3Modified = contactName3Modified;
	}

	/** 
	 * Gets the value of contactName3Modified
	 */
	public boolean isContactName3Modified()
	{
		return contactName3Modified;
	}

	/**
	 * Method 'getContactTitle3'
	 * 
	 * @return String
	 */
	public String getContactTitle3()
	{
		return contactTitle3;
	}

	/**
	 * Method 'setContactTitle3'
	 * 
	 * @param contactTitle3
	 */
	public void setContactTitle3(String contactTitle3)
	{
		this.contactTitle3 = contactTitle3;
		this.contactTitle3Modified = true;
	}

	/** 
	 * Sets the value of contactTitle3Modified
	 */
	public void setContactTitle3Modified(boolean contactTitle3Modified)
	{
		this.contactTitle3Modified = contactTitle3Modified;
	}

	/** 
	 * Gets the value of contactTitle3Modified
	 */
	public boolean isContactTitle3Modified()
	{
		return contactTitle3Modified;
	}

	/**
	 * Method 'getEmailAddress3'
	 * 
	 * @return String
	 */
	public String getEmailAddress3()
	{
		return emailAddress3;
	}

	/**
	 * Method 'setEmailAddress3'
	 * 
	 * @param emailAddress3
	 */
	public void setEmailAddress3(String emailAddress3)
	{
		this.emailAddress3 = emailAddress3;
		this.emailAddress3Modified = true;
	}

	/** 
	 * Sets the value of emailAddress3Modified
	 */
	public void setEmailAddress3Modified(boolean emailAddress3Modified)
	{
		this.emailAddress3Modified = emailAddress3Modified;
	}

	/** 
	 * Gets the value of emailAddress3Modified
	 */
	public boolean isEmailAddress3Modified()
	{
		return emailAddress3Modified;
	}

	/**
	 * Method 'getDateCreated'
	 * 
	 * @return Date
	 */
	public Date getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Method 'setDateCreated'
	 * 
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
		this.dateCreatedModified = true;
	}

	/** 
	 * Sets the value of dateCreatedModified
	 */
	public void setDateCreatedModified(boolean dateCreatedModified)
	{
		this.dateCreatedModified = dateCreatedModified;
	}

	/** 
	 * Gets the value of dateCreatedModified
	 */
	public boolean isDateCreatedModified()
	{
		return dateCreatedModified;
	}

	/**
	 * Method 'getDateModified'
	 * 
	 * @return Date
	 */
	public Date getDateModified()
	{
		return dateModified;
	}

	/**
	 * Method 'setDateModified'
	 * 
	 * @param dateModified
	 */
	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
		this.dateModifiedModified = true;
	}

	/** 
	 * Sets the value of dateModifiedModified
	 */
	public void setDateModifiedModified(boolean dateModifiedModified)
	{
		this.dateModifiedModified = dateModifiedModified;
	}

	/** 
	 * Gets the value of dateModifiedModified
	 */
	public boolean isDateModifiedModified()
	{
		return dateModifiedModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Contactsreferences)) {
			return false;
		}
		
		final Contactsreferences _cast = (Contactsreferences) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (supplierId != _cast.supplierId) {
			return false;
		}
		
		if (supplierIdModified != _cast.supplierIdModified) {
			return false;
		}
		
		if (isHpTrader == null ? _cast.isHpTrader != isHpTrader : !isHpTrader.equals( _cast.isHpTrader )) {
			return false;
		}
		
		if (isHpTraderModified != _cast.isHpTraderModified) {
			return false;
		}
		
		if (contractTitle == null ? _cast.contractTitle != contractTitle : !contractTitle.equals( _cast.contractTitle )) {
			return false;
		}
		
		if (contractTitleModified != _cast.contractTitleModified) {
			return false;
		}
		
		if (contractRef == null ? _cast.contractRef != contractRef : !contractRef.equals( _cast.contractRef )) {
			return false;
		}
		
		if (contractRefModified != _cast.contractRefModified) {
			return false;
		}
		
		if (expiryDate == null ? _cast.expiryDate != expiryDate : !expiryDate.equals( _cast.expiryDate )) {
			return false;
		}
		
		if (expiryDateModified != _cast.expiryDateModified) {
			return false;
		}
		
		if (hpContractMgr == null ? _cast.hpContractMgr != hpContractMgr : !hpContractMgr.equals( _cast.hpContractMgr )) {
			return false;
		}
		
		if (hpContractMgrModified != _cast.hpContractMgrModified) {
			return false;
		}
		
		if (divName1 == null ? _cast.divName1 != divName1 : !divName1.equals( _cast.divName1 )) {
			return false;
		}
		
		if (divName1Modified != _cast.divName1Modified) {
			return false;
		}
		
		if (contactName1 == null ? _cast.contactName1 != contactName1 : !contactName1.equals( _cast.contactName1 )) {
			return false;
		}
		
		if (contactName1Modified != _cast.contactName1Modified) {
			return false;
		}
		
		if (siteLocation1 == null ? _cast.siteLocation1 != siteLocation1 : !siteLocation1.equals( _cast.siteLocation1 )) {
			return false;
		}
		
		if (siteLocation1Modified != _cast.siteLocation1Modified) {
			return false;
		}
		
		if (lastMeetingDate1 == null ? _cast.lastMeetingDate1 != lastMeetingDate1 : !lastMeetingDate1.equals( _cast.lastMeetingDate1 )) {
			return false;
		}
		
		if (lastMeetingDate1Modified != _cast.lastMeetingDate1Modified) {
			return false;
		}
		
		if (approxServicePeriod1 == null ? _cast.approxServicePeriod1 != approxServicePeriod1 : !approxServicePeriod1.equals( _cast.approxServicePeriod1 )) {
			return false;
		}
		
		if (approxServicePeriod1Modified != _cast.approxServicePeriod1Modified) {
			return false;
		}
		
		if (divName2 == null ? _cast.divName2 != divName2 : !divName2.equals( _cast.divName2 )) {
			return false;
		}
		
		if (divName2Modified != _cast.divName2Modified) {
			return false;
		}
		
		if (hpContactName2 == null ? _cast.hpContactName2 != hpContactName2 : !hpContactName2.equals( _cast.hpContactName2 )) {
			return false;
		}
		
		if (hpContactName2Modified != _cast.hpContactName2Modified) {
			return false;
		}
		
		if (siteLocation2 == null ? _cast.siteLocation2 != siteLocation2 : !siteLocation2.equals( _cast.siteLocation2 )) {
			return false;
		}
		
		if (siteLocation2Modified != _cast.siteLocation2Modified) {
			return false;
		}
		
		if (lastMeetingDate2 == null ? _cast.lastMeetingDate2 != lastMeetingDate2 : !lastMeetingDate2.equals( _cast.lastMeetingDate2 )) {
			return false;
		}
		
		if (lastMeetingDate2Modified != _cast.lastMeetingDate2Modified) {
			return false;
		}
		
		if (approxServicePeriod2 == null ? _cast.approxServicePeriod2 != approxServicePeriod2 : !approxServicePeriod2.equals( _cast.approxServicePeriod2 )) {
			return false;
		}
		
		if (approxServicePeriod2Modified != _cast.approxServicePeriod2Modified) {
			return false;
		}
		
		if (divName3 == null ? _cast.divName3 != divName3 : !divName3.equals( _cast.divName3 )) {
			return false;
		}
		
		if (divName3Modified != _cast.divName3Modified) {
			return false;
		}
		
		if (hpContactName3 == null ? _cast.hpContactName3 != hpContactName3 : !hpContactName3.equals( _cast.hpContactName3 )) {
			return false;
		}
		
		if (hpContactName3Modified != _cast.hpContactName3Modified) {
			return false;
		}
		
		if (siteLocation3 == null ? _cast.siteLocation3 != siteLocation3 : !siteLocation3.equals( _cast.siteLocation3 )) {
			return false;
		}
		
		if (siteLocation3Modified != _cast.siteLocation3Modified) {
			return false;
		}
		
		if (lastMeetingDate3 == null ? _cast.lastMeetingDate3 != lastMeetingDate3 : !lastMeetingDate3.equals( _cast.lastMeetingDate3 )) {
			return false;
		}
		
		if (lastMeetingDate3Modified != _cast.lastMeetingDate3Modified) {
			return false;
		}
		
		if (approxServicePeriod3 == null ? _cast.approxServicePeriod3 != approxServicePeriod3 : !approxServicePeriod3.equals( _cast.approxServicePeriod3 )) {
			return false;
		}
		
		if (approxServicePeriod3Modified != _cast.approxServicePeriod3Modified) {
			return false;
		}
		
		if (organization1 == null ? _cast.organization1 != organization1 : !organization1.equals( _cast.organization1 )) {
			return false;
		}
		
		if (organization1Modified != _cast.organization1Modified) {
			return false;
		}
		
		if (hpContactName1 == null ? _cast.hpContactName1 != hpContactName1 : !hpContactName1.equals( _cast.hpContactName1 )) {
			return false;
		}
		
		if (hpContactName1Modified != _cast.hpContactName1Modified) {
			return false;
		}
		
		if (contactTitle1 == null ? _cast.contactTitle1 != contactTitle1 : !contactTitle1.equals( _cast.contactTitle1 )) {
			return false;
		}
		
		if (contactTitle1Modified != _cast.contactTitle1Modified) {
			return false;
		}
		
		if (emailAddress1 == null ? _cast.emailAddress1 != emailAddress1 : !emailAddress1.equals( _cast.emailAddress1 )) {
			return false;
		}
		
		if (emailAddress1Modified != _cast.emailAddress1Modified) {
			return false;
		}
		
		if (organization2 == null ? _cast.organization2 != organization2 : !organization2.equals( _cast.organization2 )) {
			return false;
		}
		
		if (organization2Modified != _cast.organization2Modified) {
			return false;
		}
		
		if (contactName2 == null ? _cast.contactName2 != contactName2 : !contactName2.equals( _cast.contactName2 )) {
			return false;
		}
		
		if (contactName2Modified != _cast.contactName2Modified) {
			return false;
		}
		
		if (contactTitle2 == null ? _cast.contactTitle2 != contactTitle2 : !contactTitle2.equals( _cast.contactTitle2 )) {
			return false;
		}
		
		if (contactTitle2Modified != _cast.contactTitle2Modified) {
			return false;
		}
		
		if (emailAddress2 == null ? _cast.emailAddress2 != emailAddress2 : !emailAddress2.equals( _cast.emailAddress2 )) {
			return false;
		}
		
		if (emailAddress2Modified != _cast.emailAddress2Modified) {
			return false;
		}
		
		if (organization3 == null ? _cast.organization3 != organization3 : !organization3.equals( _cast.organization3 )) {
			return false;
		}
		
		if (organization3Modified != _cast.organization3Modified) {
			return false;
		}
		
		if (contactName3 == null ? _cast.contactName3 != contactName3 : !contactName3.equals( _cast.contactName3 )) {
			return false;
		}
		
		if (contactName3Modified != _cast.contactName3Modified) {
			return false;
		}
		
		if (contactTitle3 == null ? _cast.contactTitle3 != contactTitle3 : !contactTitle3.equals( _cast.contactTitle3 )) {
			return false;
		}
		
		if (contactTitle3Modified != _cast.contactTitle3Modified) {
			return false;
		}
		
		if (emailAddress3 == null ? _cast.emailAddress3 != emailAddress3 : !emailAddress3.equals( _cast.emailAddress3 )) {
			return false;
		}
		
		if (emailAddress3Modified != _cast.emailAddress3Modified) {
			return false;
		}
		
		if (dateCreated == null ? _cast.dateCreated != dateCreated : !dateCreated.equals( _cast.dateCreated )) {
			return false;
		}
		
		if (dateCreatedModified != _cast.dateCreatedModified) {
			return false;
		}
		
		if (dateModified == null ? _cast.dateModified != dateModified : !dateModified.equals( _cast.dateModified )) {
			return false;
		}
		
		if (dateModifiedModified != _cast.dateModifiedModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + supplierId;
		_hashCode = 29 * _hashCode + (supplierIdModified ? 1 : 0);
		if (isHpTrader != null) {
			_hashCode = 29 * _hashCode + isHpTrader.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (isHpTraderModified ? 1 : 0);
		if (contractTitle != null) {
			_hashCode = 29 * _hashCode + contractTitle.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contractTitleModified ? 1 : 0);
		if (contractRef != null) {
			_hashCode = 29 * _hashCode + contractRef.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contractRefModified ? 1 : 0);
		if (expiryDate != null) {
			_hashCode = 29 * _hashCode + expiryDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (expiryDateModified ? 1 : 0);
		if (hpContractMgr != null) {
			_hashCode = 29 * _hashCode + hpContractMgr.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (hpContractMgrModified ? 1 : 0);
		if (divName1 != null) {
			_hashCode = 29 * _hashCode + divName1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (divName1Modified ? 1 : 0);
		if (contactName1 != null) {
			_hashCode = 29 * _hashCode + contactName1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactName1Modified ? 1 : 0);
		if (siteLocation1 != null) {
			_hashCode = 29 * _hashCode + siteLocation1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (siteLocation1Modified ? 1 : 0);
		if (lastMeetingDate1 != null) {
			_hashCode = 29 * _hashCode + lastMeetingDate1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (lastMeetingDate1Modified ? 1 : 0);
		if (approxServicePeriod1 != null) {
			_hashCode = 29 * _hashCode + approxServicePeriod1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (approxServicePeriod1Modified ? 1 : 0);
		if (divName2 != null) {
			_hashCode = 29 * _hashCode + divName2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (divName2Modified ? 1 : 0);
		if (hpContactName2 != null) {
			_hashCode = 29 * _hashCode + hpContactName2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (hpContactName2Modified ? 1 : 0);
		if (siteLocation2 != null) {
			_hashCode = 29 * _hashCode + siteLocation2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (siteLocation2Modified ? 1 : 0);
		if (lastMeetingDate2 != null) {
			_hashCode = 29 * _hashCode + lastMeetingDate2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (lastMeetingDate2Modified ? 1 : 0);
		if (approxServicePeriod2 != null) {
			_hashCode = 29 * _hashCode + approxServicePeriod2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (approxServicePeriod2Modified ? 1 : 0);
		if (divName3 != null) {
			_hashCode = 29 * _hashCode + divName3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (divName3Modified ? 1 : 0);
		if (hpContactName3 != null) {
			_hashCode = 29 * _hashCode + hpContactName3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (hpContactName3Modified ? 1 : 0);
		if (siteLocation3 != null) {
			_hashCode = 29 * _hashCode + siteLocation3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (siteLocation3Modified ? 1 : 0);
		if (lastMeetingDate3 != null) {
			_hashCode = 29 * _hashCode + lastMeetingDate3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (lastMeetingDate3Modified ? 1 : 0);
		if (approxServicePeriod3 != null) {
			_hashCode = 29 * _hashCode + approxServicePeriod3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (approxServicePeriod3Modified ? 1 : 0);
		if (organization1 != null) {
			_hashCode = 29 * _hashCode + organization1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (organization1Modified ? 1 : 0);
		if (hpContactName1 != null) {
			_hashCode = 29 * _hashCode + hpContactName1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (hpContactName1Modified ? 1 : 0);
		if (contactTitle1 != null) {
			_hashCode = 29 * _hashCode + contactTitle1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactTitle1Modified ? 1 : 0);
		if (emailAddress1 != null) {
			_hashCode = 29 * _hashCode + emailAddress1.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (emailAddress1Modified ? 1 : 0);
		if (organization2 != null) {
			_hashCode = 29 * _hashCode + organization2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (organization2Modified ? 1 : 0);
		if (contactName2 != null) {
			_hashCode = 29 * _hashCode + contactName2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactName2Modified ? 1 : 0);
		if (contactTitle2 != null) {
			_hashCode = 29 * _hashCode + contactTitle2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactTitle2Modified ? 1 : 0);
		if (emailAddress2 != null) {
			_hashCode = 29 * _hashCode + emailAddress2.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (emailAddress2Modified ? 1 : 0);
		if (organization3 != null) {
			_hashCode = 29 * _hashCode + organization3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (organization3Modified ? 1 : 0);
		if (contactName3 != null) {
			_hashCode = 29 * _hashCode + contactName3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactName3Modified ? 1 : 0);
		if (contactTitle3 != null) {
			_hashCode = 29 * _hashCode + contactTitle3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contactTitle3Modified ? 1 : 0);
		if (emailAddress3 != null) {
			_hashCode = 29 * _hashCode + emailAddress3.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (emailAddress3Modified ? 1 : 0);
		if (dateCreated != null) {
			_hashCode = 29 * _hashCode + dateCreated.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (dateCreatedModified ? 1 : 0);
		if (dateModified != null) {
			_hashCode = 29 * _hashCode + dateModified.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (dateModifiedModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ContactsreferencesPk
	 */
	public ContactsreferencesPk createPk()
	{
		return new ContactsreferencesPk(id, supplierId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.hp.supplier.dto.Contactsreferences: " );
		ret.append( "id=" + id );
		ret.append( ", supplierId=" + supplierId );
		ret.append( ", isHpTrader=" + isHpTrader );
		ret.append( ", contractTitle=" + contractTitle );
		ret.append( ", contractRef=" + contractRef );
		ret.append( ", expiryDate=" + expiryDate );
		ret.append( ", hpContractMgr=" + hpContractMgr );
		ret.append( ", divName1=" + divName1 );
		ret.append( ", contactName1=" + contactName1 );
		ret.append( ", siteLocation1=" + siteLocation1 );
		ret.append( ", lastMeetingDate1=" + lastMeetingDate1 );
		ret.append( ", approxServicePeriod1=" + approxServicePeriod1 );
		ret.append( ", divName2=" + divName2 );
		ret.append( ", hpContactName2=" + hpContactName2 );
		ret.append( ", siteLocation2=" + siteLocation2 );
		ret.append( ", lastMeetingDate2=" + lastMeetingDate2 );
		ret.append( ", approxServicePeriod2=" + approxServicePeriod2 );
		ret.append( ", divName3=" + divName3 );
		ret.append( ", hpContactName3=" + hpContactName3 );
		ret.append( ", siteLocation3=" + siteLocation3 );
		ret.append( ", lastMeetingDate3=" + lastMeetingDate3 );
		ret.append( ", approxServicePeriod3=" + approxServicePeriod3 );
		ret.append( ", organization1=" + organization1 );
		ret.append( ", hpContactName1=" + hpContactName1 );
		ret.append( ", contactTitle1=" + contactTitle1 );
		ret.append( ", emailAddress1=" + emailAddress1 );
		ret.append( ", organization2=" + organization2 );
		ret.append( ", contactName2=" + contactName2 );
		ret.append( ", contactTitle2=" + contactTitle2 );
		ret.append( ", emailAddress2=" + emailAddress2 );
		ret.append( ", organization3=" + organization3 );
		ret.append( ", contactName3=" + contactName3 );
		ret.append( ", contactTitle3=" + contactTitle3 );
		ret.append( ", emailAddress3=" + emailAddress3 );
		ret.append( ", dateCreated=" + dateCreated );
		ret.append( ", dateModified=" + dateModified );
		return ret.toString();
	}

}
