/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hp.supplier.dto;

import com.hp.supplier.dao.*;
import com.hp.supplier.factory.*;
import com.hp.supplier.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Markets implements Serializable
{
	/** 
	 * This attribute maps to the column id in the markets table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column supplier_id in the markets table.
	 */
	protected int supplierId;

	/** 
	 * This attribute represents whether the attribute supplierId has been modified since being read from the database.
	 */
	protected boolean supplierIdModified = false;

	/** 
	 * This attribute maps to the column england in the markets table.
	 */
	protected String england;

	/** 
	 * This attribute represents whether the attribute england has been modified since being read from the database.
	 */
	protected boolean englandModified = false;

	/** 
	 * This attribute maps to the column northen_ireland in the markets table.
	 */
	protected String northenIreland;

	/** 
	 * This attribute represents whether the attribute northenIreland has been modified since being read from the database.
	 */
	protected boolean northenIrelandModified = false;

	/** 
	 * This attribute maps to the column scotland in the markets table.
	 */
	protected String scotland;

	/** 
	 * This attribute represents whether the attribute scotland has been modified since being read from the database.
	 */
	protected boolean scotlandModified = false;

	/** 
	 * This attribute maps to the column wales in the markets table.
	 */
	protected String wales;

	/** 
	 * This attribute represents whether the attribute wales has been modified since being read from the database.
	 */
	protected boolean walesModified = false;

	/** 
	 * This attribute maps to the column africa in the markets table.
	 */
	protected String africa;

	/** 
	 * This attribute represents whether the attribute africa has been modified since being read from the database.
	 */
	protected boolean africaModified = false;

	/** 
	 * This attribute maps to the column asia_pacific in the markets table.
	 */
	protected String asiaPacific;

	/** 
	 * This attribute represents whether the attribute asiaPacific has been modified since being read from the database.
	 */
	protected boolean asiaPacificModified = false;

	/** 
	 * This attribute maps to the column australia in the markets table.
	 */
	protected String australia;

	/** 
	 * This attribute represents whether the attribute australia has been modified since being read from the database.
	 */
	protected boolean australiaModified = false;

	/** 
	 * This attribute maps to the column canada in the markets table.
	 */
	protected String canada;

	/** 
	 * This attribute represents whether the attribute canada has been modified since being read from the database.
	 */
	protected boolean canadaModified = false;

	/** 
	 * This attribute maps to the column europe in the markets table.
	 */
	protected String europe;

	/** 
	 * This attribute represents whether the attribute europe has been modified since being read from the database.
	 */
	protected boolean europeModified = false;

	/** 
	 * This attribute maps to the column latin_america in the markets table.
	 */
	protected String latinAmerica;

	/** 
	 * This attribute represents whether the attribute latinAmerica has been modified since being read from the database.
	 */
	protected boolean latinAmericaModified = false;

	/** 
	 * This attribute maps to the column mexico in the markets table.
	 */
	protected String mexico;

	/** 
	 * This attribute represents whether the attribute mexico has been modified since being read from the database.
	 */
	protected boolean mexicoModified = false;

	/** 
	 * This attribute maps to the column united_stated in the markets table.
	 */
	protected String unitedStated;

	/** 
	 * This attribute represents whether the attribute unitedStated has been modified since being read from the database.
	 */
	protected boolean unitedStatedModified = false;

	/** 
	 * This attribute maps to the column date_created in the markets table.
	 */
	protected Date dateCreated;

	/** 
	 * This attribute represents whether the attribute dateCreated has been modified since being read from the database.
	 */
	protected boolean dateCreatedModified = false;

	/** 
	 * This attribute maps to the column date_modification in the markets table.
	 */
	protected Date dateModification;

	/** 
	 * This attribute represents whether the attribute dateModification has been modified since being read from the database.
	 */
	protected boolean dateModificationModified = false;

	/**
	 * Method 'Markets'
	 * 
	 */
	public Markets()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getSupplierId'
	 * 
	 * @return int
	 */
	public int getSupplierId()
	{
		return supplierId;
	}

	/**
	 * Method 'setSupplierId'
	 * 
	 * @param supplierId
	 */
	public void setSupplierId(int supplierId)
	{
		this.supplierId = supplierId;
		this.supplierIdModified = true;
	}

	/** 
	 * Sets the value of supplierIdModified
	 */
	public void setSupplierIdModified(boolean supplierIdModified)
	{
		this.supplierIdModified = supplierIdModified;
	}

	/** 
	 * Gets the value of supplierIdModified
	 */
	public boolean isSupplierIdModified()
	{
		return supplierIdModified;
	}

	/**
	 * Method 'getEngland'
	 * 
	 * @return String
	 */
	public String getEngland()
	{
		return england;
	}

	/**
	 * Method 'setEngland'
	 * 
	 * @param england
	 */
	public void setEngland(String england)
	{
		this.england = england;
		this.englandModified = true;
	}

	/** 
	 * Sets the value of englandModified
	 */
	public void setEnglandModified(boolean englandModified)
	{
		this.englandModified = englandModified;
	}

	/** 
	 * Gets the value of englandModified
	 */
	public boolean isEnglandModified()
	{
		return englandModified;
	}

	/**
	 * Method 'getNorthenIreland'
	 * 
	 * @return String
	 */
	public String getNorthenIreland()
	{
		return northenIreland;
	}

	/**
	 * Method 'setNorthenIreland'
	 * 
	 * @param northenIreland
	 */
	public void setNorthenIreland(String northenIreland)
	{
		this.northenIreland = northenIreland;
		this.northenIrelandModified = true;
	}

	/** 
	 * Sets the value of northenIrelandModified
	 */
	public void setNorthenIrelandModified(boolean northenIrelandModified)
	{
		this.northenIrelandModified = northenIrelandModified;
	}

	/** 
	 * Gets the value of northenIrelandModified
	 */
	public boolean isNorthenIrelandModified()
	{
		return northenIrelandModified;
	}

	/**
	 * Method 'getScotland'
	 * 
	 * @return String
	 */
	public String getScotland()
	{
		return scotland;
	}

	/**
	 * Method 'setScotland'
	 * 
	 * @param scotland
	 */
	public void setScotland(String scotland)
	{
		this.scotland = scotland;
		this.scotlandModified = true;
	}

	/** 
	 * Sets the value of scotlandModified
	 */
	public void setScotlandModified(boolean scotlandModified)
	{
		this.scotlandModified = scotlandModified;
	}

	/** 
	 * Gets the value of scotlandModified
	 */
	public boolean isScotlandModified()
	{
		return scotlandModified;
	}

	/**
	 * Method 'getWales'
	 * 
	 * @return String
	 */
	public String getWales()
	{
		return wales;
	}

	/**
	 * Method 'setWales'
	 * 
	 * @param wales
	 */
	public void setWales(String wales)
	{
		this.wales = wales;
		this.walesModified = true;
	}

	/** 
	 * Sets the value of walesModified
	 */
	public void setWalesModified(boolean walesModified)
	{
		this.walesModified = walesModified;
	}

	/** 
	 * Gets the value of walesModified
	 */
	public boolean isWalesModified()
	{
		return walesModified;
	}

	/**
	 * Method 'getAfrica'
	 * 
	 * @return String
	 */
	public String getAfrica()
	{
		return africa;
	}

	/**
	 * Method 'setAfrica'
	 * 
	 * @param africa
	 */
	public void setAfrica(String africa)
	{
		this.africa = africa;
		this.africaModified = true;
	}

	/** 
	 * Sets the value of africaModified
	 */
	public void setAfricaModified(boolean africaModified)
	{
		this.africaModified = africaModified;
	}

	/** 
	 * Gets the value of africaModified
	 */
	public boolean isAfricaModified()
	{
		return africaModified;
	}

	/**
	 * Method 'getAsiaPacific'
	 * 
	 * @return String
	 */
	public String getAsiaPacific()
	{
		return asiaPacific;
	}

	/**
	 * Method 'setAsiaPacific'
	 * 
	 * @param asiaPacific
	 */
	public void setAsiaPacific(String asiaPacific)
	{
		this.asiaPacific = asiaPacific;
		this.asiaPacificModified = true;
	}

	/** 
	 * Sets the value of asiaPacificModified
	 */
	public void setAsiaPacificModified(boolean asiaPacificModified)
	{
		this.asiaPacificModified = asiaPacificModified;
	}

	/** 
	 * Gets the value of asiaPacificModified
	 */
	public boolean isAsiaPacificModified()
	{
		return asiaPacificModified;
	}

	/**
	 * Method 'getAustralia'
	 * 
	 * @return String
	 */
	public String getAustralia()
	{
		return australia;
	}

	/**
	 * Method 'setAustralia'
	 * 
	 * @param australia
	 */
	public void setAustralia(String australia)
	{
		this.australia = australia;
		this.australiaModified = true;
	}

	/** 
	 * Sets the value of australiaModified
	 */
	public void setAustraliaModified(boolean australiaModified)
	{
		this.australiaModified = australiaModified;
	}

	/** 
	 * Gets the value of australiaModified
	 */
	public boolean isAustraliaModified()
	{
		return australiaModified;
	}

	/**
	 * Method 'getCanada'
	 * 
	 * @return String
	 */
	public String getCanada()
	{
		return canada;
	}

	/**
	 * Method 'setCanada'
	 * 
	 * @param canada
	 */
	public void setCanada(String canada)
	{
		this.canada = canada;
		this.canadaModified = true;
	}

	/** 
	 * Sets the value of canadaModified
	 */
	public void setCanadaModified(boolean canadaModified)
	{
		this.canadaModified = canadaModified;
	}

	/** 
	 * Gets the value of canadaModified
	 */
	public boolean isCanadaModified()
	{
		return canadaModified;
	}

	/**
	 * Method 'getEurope'
	 * 
	 * @return String
	 */
	public String getEurope()
	{
		return europe;
	}

	/**
	 * Method 'setEurope'
	 * 
	 * @param europe
	 */
	public void setEurope(String europe)
	{
		this.europe = europe;
		this.europeModified = true;
	}

	/** 
	 * Sets the value of europeModified
	 */
	public void setEuropeModified(boolean europeModified)
	{
		this.europeModified = europeModified;
	}

	/** 
	 * Gets the value of europeModified
	 */
	public boolean isEuropeModified()
	{
		return europeModified;
	}

	/**
	 * Method 'getLatinAmerica'
	 * 
	 * @return String
	 */
	public String getLatinAmerica()
	{
		return latinAmerica;
	}

	/**
	 * Method 'setLatinAmerica'
	 * 
	 * @param latinAmerica
	 */
	public void setLatinAmerica(String latinAmerica)
	{
		this.latinAmerica = latinAmerica;
		this.latinAmericaModified = true;
	}

	/** 
	 * Sets the value of latinAmericaModified
	 */
	public void setLatinAmericaModified(boolean latinAmericaModified)
	{
		this.latinAmericaModified = latinAmericaModified;
	}

	/** 
	 * Gets the value of latinAmericaModified
	 */
	public boolean isLatinAmericaModified()
	{
		return latinAmericaModified;
	}

	/**
	 * Method 'getMexico'
	 * 
	 * @return String
	 */
	public String getMexico()
	{
		return mexico;
	}

	/**
	 * Method 'setMexico'
	 * 
	 * @param mexico
	 */
	public void setMexico(String mexico)
	{
		this.mexico = mexico;
		this.mexicoModified = true;
	}

	/** 
	 * Sets the value of mexicoModified
	 */
	public void setMexicoModified(boolean mexicoModified)
	{
		this.mexicoModified = mexicoModified;
	}

	/** 
	 * Gets the value of mexicoModified
	 */
	public boolean isMexicoModified()
	{
		return mexicoModified;
	}

	/**
	 * Method 'getUnitedStated'
	 * 
	 * @return String
	 */
	public String getUnitedStated()
	{
		return unitedStated;
	}

	/**
	 * Method 'setUnitedStated'
	 * 
	 * @param unitedStated
	 */
	public void setUnitedStated(String unitedStated)
	{
		this.unitedStated = unitedStated;
		this.unitedStatedModified = true;
	}

	/** 
	 * Sets the value of unitedStatedModified
	 */
	public void setUnitedStatedModified(boolean unitedStatedModified)
	{
		this.unitedStatedModified = unitedStatedModified;
	}

	/** 
	 * Gets the value of unitedStatedModified
	 */
	public boolean isUnitedStatedModified()
	{
		return unitedStatedModified;
	}

	/**
	 * Method 'getDateCreated'
	 * 
	 * @return Date
	 */
	public Date getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Method 'setDateCreated'
	 * 
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
		this.dateCreatedModified = true;
	}

	/** 
	 * Sets the value of dateCreatedModified
	 */
	public void setDateCreatedModified(boolean dateCreatedModified)
	{
		this.dateCreatedModified = dateCreatedModified;
	}

	/** 
	 * Gets the value of dateCreatedModified
	 */
	public boolean isDateCreatedModified()
	{
		return dateCreatedModified;
	}

	/**
	 * Method 'getDateModification'
	 * 
	 * @return Date
	 */
	public Date getDateModification()
	{
		return dateModification;
	}

	/**
	 * Method 'setDateModification'
	 * 
	 * @param dateModification
	 */
	public void setDateModification(Date dateModification)
	{
		this.dateModification = dateModification;
		this.dateModificationModified = true;
	}

	/** 
	 * Sets the value of dateModificationModified
	 */
	public void setDateModificationModified(boolean dateModificationModified)
	{
		this.dateModificationModified = dateModificationModified;
	}

	/** 
	 * Gets the value of dateModificationModified
	 */
	public boolean isDateModificationModified()
	{
		return dateModificationModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Markets)) {
			return false;
		}
		
		final Markets _cast = (Markets) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (supplierId != _cast.supplierId) {
			return false;
		}
		
		if (supplierIdModified != _cast.supplierIdModified) {
			return false;
		}
		
		if (england == null ? _cast.england != england : !england.equals( _cast.england )) {
			return false;
		}
		
		if (englandModified != _cast.englandModified) {
			return false;
		}
		
		if (northenIreland == null ? _cast.northenIreland != northenIreland : !northenIreland.equals( _cast.northenIreland )) {
			return false;
		}
		
		if (northenIrelandModified != _cast.northenIrelandModified) {
			return false;
		}
		
		if (scotland == null ? _cast.scotland != scotland : !scotland.equals( _cast.scotland )) {
			return false;
		}
		
		if (scotlandModified != _cast.scotlandModified) {
			return false;
		}
		
		if (wales == null ? _cast.wales != wales : !wales.equals( _cast.wales )) {
			return false;
		}
		
		if (walesModified != _cast.walesModified) {
			return false;
		}
		
		if (africa == null ? _cast.africa != africa : !africa.equals( _cast.africa )) {
			return false;
		}
		
		if (africaModified != _cast.africaModified) {
			return false;
		}
		
		if (asiaPacific == null ? _cast.asiaPacific != asiaPacific : !asiaPacific.equals( _cast.asiaPacific )) {
			return false;
		}
		
		if (asiaPacificModified != _cast.asiaPacificModified) {
			return false;
		}
		
		if (australia == null ? _cast.australia != australia : !australia.equals( _cast.australia )) {
			return false;
		}
		
		if (australiaModified != _cast.australiaModified) {
			return false;
		}
		
		if (canada == null ? _cast.canada != canada : !canada.equals( _cast.canada )) {
			return false;
		}
		
		if (canadaModified != _cast.canadaModified) {
			return false;
		}
		
		if (europe == null ? _cast.europe != europe : !europe.equals( _cast.europe )) {
			return false;
		}
		
		if (europeModified != _cast.europeModified) {
			return false;
		}
		
		if (latinAmerica == null ? _cast.latinAmerica != latinAmerica : !latinAmerica.equals( _cast.latinAmerica )) {
			return false;
		}
		
		if (latinAmericaModified != _cast.latinAmericaModified) {
			return false;
		}
		
		if (mexico == null ? _cast.mexico != mexico : !mexico.equals( _cast.mexico )) {
			return false;
		}
		
		if (mexicoModified != _cast.mexicoModified) {
			return false;
		}
		
		if (unitedStated == null ? _cast.unitedStated != unitedStated : !unitedStated.equals( _cast.unitedStated )) {
			return false;
		}
		
		if (unitedStatedModified != _cast.unitedStatedModified) {
			return false;
		}
		
		if (dateCreated == null ? _cast.dateCreated != dateCreated : !dateCreated.equals( _cast.dateCreated )) {
			return false;
		}
		
		if (dateCreatedModified != _cast.dateCreatedModified) {
			return false;
		}
		
		if (dateModification == null ? _cast.dateModification != dateModification : !dateModification.equals( _cast.dateModification )) {
			return false;
		}
		
		if (dateModificationModified != _cast.dateModificationModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + supplierId;
		_hashCode = 29 * _hashCode + (supplierIdModified ? 1 : 0);
		if (england != null) {
			_hashCode = 29 * _hashCode + england.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (englandModified ? 1 : 0);
		if (northenIreland != null) {
			_hashCode = 29 * _hashCode + northenIreland.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (northenIrelandModified ? 1 : 0);
		if (scotland != null) {
			_hashCode = 29 * _hashCode + scotland.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (scotlandModified ? 1 : 0);
		if (wales != null) {
			_hashCode = 29 * _hashCode + wales.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (walesModified ? 1 : 0);
		if (africa != null) {
			_hashCode = 29 * _hashCode + africa.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (africaModified ? 1 : 0);
		if (asiaPacific != null) {
			_hashCode = 29 * _hashCode + asiaPacific.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (asiaPacificModified ? 1 : 0);
		if (australia != null) {
			_hashCode = 29 * _hashCode + australia.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (australiaModified ? 1 : 0);
		if (canada != null) {
			_hashCode = 29 * _hashCode + canada.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (canadaModified ? 1 : 0);
		if (europe != null) {
			_hashCode = 29 * _hashCode + europe.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (europeModified ? 1 : 0);
		if (latinAmerica != null) {
			_hashCode = 29 * _hashCode + latinAmerica.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (latinAmericaModified ? 1 : 0);
		if (mexico != null) {
			_hashCode = 29 * _hashCode + mexico.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (mexicoModified ? 1 : 0);
		if (unitedStated != null) {
			_hashCode = 29 * _hashCode + unitedStated.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (unitedStatedModified ? 1 : 0);
		if (dateCreated != null) {
			_hashCode = 29 * _hashCode + dateCreated.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (dateCreatedModified ? 1 : 0);
		if (dateModification != null) {
			_hashCode = 29 * _hashCode + dateModification.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (dateModificationModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MarketsPk
	 */
	public MarketsPk createPk()
	{
		return new MarketsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.hp.supplier.dto.Markets: " );
		ret.append( "id=" + id );
		ret.append( ", supplierId=" + supplierId );
		ret.append( ", england=" + england );
		ret.append( ", northenIreland=" + northenIreland );
		ret.append( ", scotland=" + scotland );
		ret.append( ", wales=" + wales );
		ret.append( ", africa=" + africa );
		ret.append( ", asiaPacific=" + asiaPacific );
		ret.append( ", australia=" + australia );
		ret.append( ", canada=" + canada );
		ret.append( ", europe=" + europe );
		ret.append( ", latinAmerica=" + latinAmerica );
		ret.append( ", mexico=" + mexico );
		ret.append( ", unitedStated=" + unitedStated );
		ret.append( ", dateCreated=" + dateCreated );
		ret.append( ", dateModification=" + dateModification );
		return ret.toString();
	}

}
