/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.edu.iijnm.dto;

import com.edu.iijnm.dao.*;
import com.edu.iijnm.factory.*;
import com.edu.iijnm.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class InterestAttachmentsDetails implements Serializable
{
	/** 
	 * This attribute maps to the column id in the interest_attachments_details table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column student_id in the interest_attachments_details table.
	 */
	protected int studentId;

	/** 
	 * This attribute represents whether the primitive attribute studentId is null.
	 */
	protected boolean studentIdNull = true;

	/** 
	 * This attribute represents whether the attribute studentId has been modified since being read from the database.
	 */
	protected boolean studentIdModified = false;

	/** 
	 * This attribute maps to the column accomplishments in the interest_attachments_details table.
	 */
	protected String accomplishments;

	/** 
	 * This attribute represents whether the attribute accomplishments has been modified since being read from the database.
	 */
	protected boolean accomplishmentsModified = false;

	/** 
	 * This attribute maps to the column special_skills in the interest_attachments_details table.
	 */
	protected String specialSkills;

	/** 
	 * This attribute represents whether the attribute specialSkills has been modified since being read from the database.
	 */
	protected boolean specialSkillsModified = false;

	/** 
	 * This attribute maps to the column hobbies in the interest_attachments_details table.
	 */
	protected String hobbies;

	/** 
	 * This attribute represents whether the attribute hobbies has been modified since being read from the database.
	 */
	protected boolean hobbiesModified = false;

	/** 
	 * This attribute maps to the column other_interests in the interest_attachments_details table.
	 */
	protected String otherInterests;

	/** 
	 * This attribute represents whether the attribute otherInterests has been modified since being read from the database.
	 */
	protected boolean otherInterestsModified = false;

	/** 
	 * This attribute maps to the column upload_reference in the interest_attachments_details table.
	 */
	protected byte[] uploadReference;

	/** 
	 * This attribute represents whether the attribute uploadReference has been modified since being read from the database.
	 */
	protected boolean uploadReferenceModified = false;

	/** 
	 * This attribute maps to the column academic_certificates in the interest_attachments_details table.
	 */
	protected byte[] academicCertificates;

	/** 
	 * This attribute represents whether the attribute academicCertificates has been modified since being read from the database.
	 */
	protected boolean academicCertificatesModified = false;

	/** 
	 * This attribute maps to the column supporting_docs in the interest_attachments_details table.
	 */
	protected byte[] supportingDocs;

	/** 
	 * This attribute represents whether the attribute supportingDocs has been modified since being read from the database.
	 */
	protected boolean supportingDocsModified = false;

	/** 
	 * This attribute maps to the column upload_essay in the interest_attachments_details table.
	 */
	protected byte[] uploadEssay;

	/** 
	 * This attribute represents whether the attribute uploadEssay has been modified since being read from the database.
	 */
	protected boolean uploadEssayModified = false;

	/** 
	 * This attribute maps to the column how_iijnm in the interest_attachments_details table.
	 */
	protected String howIijnm;

	/** 
	 * This attribute represents whether the attribute howIijnm has been modified since being read from the database.
	 */
	protected boolean howIijnmModified = false;

	/** 
	 * This attribute maps to the column created_date in the interest_attachments_details table.
	 */
	protected Date createdDate;

	/** 
	 * This attribute represents whether the attribute createdDate has been modified since being read from the database.
	 */
	protected boolean createdDateModified = false;

	/** 
	 * This attribute maps to the column modified_date in the interest_attachments_details table.
	 */
	protected Date modifiedDate;

	/** 
	 * This attribute represents whether the attribute modifiedDate has been modified since being read from the database.
	 */
	protected boolean modifiedDateModified = false;

	/**
	 * Method 'InterestAttachmentsDetails'
	 * 
	 */
	public InterestAttachmentsDetails()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getStudentId'
	 * 
	 * @return int
	 */
	public int getStudentId()
	{
		return studentId;
	}

	/**
	 * Method 'setStudentId'
	 * 
	 * @param studentId
	 */
	public void setStudentId(int studentId)
	{
		this.studentId = studentId;
		this.studentIdNull = false;
		this.studentIdModified = true;
	}

	/**
	 * Method 'setStudentIdNull'
	 * 
	 * @param value
	 */
	public void setStudentIdNull(boolean value)
	{
		this.studentIdNull = value;
		this.studentIdModified = true;
	}

	/**
	 * Method 'isStudentIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isStudentIdNull()
	{
		return studentIdNull;
	}

	/** 
	 * Sets the value of studentIdModified
	 */
	public void setStudentIdModified(boolean studentIdModified)
	{
		this.studentIdModified = studentIdModified;
	}

	/** 
	 * Gets the value of studentIdModified
	 */
	public boolean isStudentIdModified()
	{
		return studentIdModified;
	}

	/**
	 * Method 'getAccomplishments'
	 * 
	 * @return String
	 */
	public String getAccomplishments()
	{
		return accomplishments;
	}

	/**
	 * Method 'setAccomplishments'
	 * 
	 * @param accomplishments
	 */
	public void setAccomplishments(String accomplishments)
	{
		this.accomplishments = accomplishments;
		this.accomplishmentsModified = true;
	}

	/** 
	 * Sets the value of accomplishmentsModified
	 */
	public void setAccomplishmentsModified(boolean accomplishmentsModified)
	{
		this.accomplishmentsModified = accomplishmentsModified;
	}

	/** 
	 * Gets the value of accomplishmentsModified
	 */
	public boolean isAccomplishmentsModified()
	{
		return accomplishmentsModified;
	}

	/**
	 * Method 'getSpecialSkills'
	 * 
	 * @return String
	 */
	public String getSpecialSkills()
	{
		return specialSkills;
	}

	/**
	 * Method 'setSpecialSkills'
	 * 
	 * @param specialSkills
	 */
	public void setSpecialSkills(String specialSkills)
	{
		this.specialSkills = specialSkills;
		this.specialSkillsModified = true;
	}

	/** 
	 * Sets the value of specialSkillsModified
	 */
	public void setSpecialSkillsModified(boolean specialSkillsModified)
	{
		this.specialSkillsModified = specialSkillsModified;
	}

	/** 
	 * Gets the value of specialSkillsModified
	 */
	public boolean isSpecialSkillsModified()
	{
		return specialSkillsModified;
	}

	/**
	 * Method 'getHobbies'
	 * 
	 * @return String
	 */
	public String getHobbies()
	{
		return hobbies;
	}

	/**
	 * Method 'setHobbies'
	 * 
	 * @param hobbies
	 */
	public void setHobbies(String hobbies)
	{
		this.hobbies = hobbies;
		this.hobbiesModified = true;
	}

	/** 
	 * Sets the value of hobbiesModified
	 */
	public void setHobbiesModified(boolean hobbiesModified)
	{
		this.hobbiesModified = hobbiesModified;
	}

	/** 
	 * Gets the value of hobbiesModified
	 */
	public boolean isHobbiesModified()
	{
		return hobbiesModified;
	}

	/**
	 * Method 'getOtherInterests'
	 * 
	 * @return String
	 */
	public String getOtherInterests()
	{
		return otherInterests;
	}

	/**
	 * Method 'setOtherInterests'
	 * 
	 * @param otherInterests
	 */
	public void setOtherInterests(String otherInterests)
	{
		this.otherInterests = otherInterests;
		this.otherInterestsModified = true;
	}

	/** 
	 * Sets the value of otherInterestsModified
	 */
	public void setOtherInterestsModified(boolean otherInterestsModified)
	{
		this.otherInterestsModified = otherInterestsModified;
	}

	/** 
	 * Gets the value of otherInterestsModified
	 */
	public boolean isOtherInterestsModified()
	{
		return otherInterestsModified;
	}

	/**
	 * Method 'getUploadReference'
	 * 
	 * @return byte[]
	 */
	public byte[] getUploadReference()
	{
		return uploadReference;
	}

	/**
	 * Method 'setUploadReference'
	 * 
	 * @param uploadReference
	 */
	public void setUploadReference(byte[] uploadReference)
	{
		this.uploadReference = uploadReference;
		this.uploadReferenceModified = true;
	}

	/** 
	 * Sets the value of uploadReferenceModified
	 */
	public void setUploadReferenceModified(boolean uploadReferenceModified)
	{
		this.uploadReferenceModified = uploadReferenceModified;
	}

	/** 
	 * Gets the value of uploadReferenceModified
	 */
	public boolean isUploadReferenceModified()
	{
		return uploadReferenceModified;
	}

	/**
	 * Method 'getAcademicCertificates'
	 * 
	 * @return byte[]
	 */
	public byte[] getAcademicCertificates()
	{
		return academicCertificates;
	}

	/**
	 * Method 'setAcademicCertificates'
	 * 
	 * @param academicCertificates
	 */
	public void setAcademicCertificates(byte[] academicCertificates)
	{
		this.academicCertificates = academicCertificates;
		this.academicCertificatesModified = true;
	}

	/** 
	 * Sets the value of academicCertificatesModified
	 */
	public void setAcademicCertificatesModified(boolean academicCertificatesModified)
	{
		this.academicCertificatesModified = academicCertificatesModified;
	}

	/** 
	 * Gets the value of academicCertificatesModified
	 */
	public boolean isAcademicCertificatesModified()
	{
		return academicCertificatesModified;
	}

	/**
	 * Method 'getSupportingDocs'
	 * 
	 * @return byte[]
	 */
	public byte[] getSupportingDocs()
	{
		return supportingDocs;
	}

	/**
	 * Method 'setSupportingDocs'
	 * 
	 * @param supportingDocs
	 */
	public void setSupportingDocs(byte[] supportingDocs)
	{
		this.supportingDocs = supportingDocs;
		this.supportingDocsModified = true;
	}

	/** 
	 * Sets the value of supportingDocsModified
	 */
	public void setSupportingDocsModified(boolean supportingDocsModified)
	{
		this.supportingDocsModified = supportingDocsModified;
	}

	/** 
	 * Gets the value of supportingDocsModified
	 */
	public boolean isSupportingDocsModified()
	{
		return supportingDocsModified;
	}

	/**
	 * Method 'getUploadEssay'
	 * 
	 * @return byte[]
	 */
	public byte[] getUploadEssay()
	{
		return uploadEssay;
	}

	/**
	 * Method 'setUploadEssay'
	 * 
	 * @param uploadEssay
	 */
	public void setUploadEssay(byte[] uploadEssay)
	{
		this.uploadEssay = uploadEssay;
		this.uploadEssayModified = true;
	}

	/** 
	 * Sets the value of uploadEssayModified
	 */
	public void setUploadEssayModified(boolean uploadEssayModified)
	{
		this.uploadEssayModified = uploadEssayModified;
	}

	/** 
	 * Gets the value of uploadEssayModified
	 */
	public boolean isUploadEssayModified()
	{
		return uploadEssayModified;
	}

	/**
	 * Method 'getHowIijnm'
	 * 
	 * @return String
	 */
	public String getHowIijnm()
	{
		return howIijnm;
	}

	/**
	 * Method 'setHowIijnm'
	 * 
	 * @param howIijnm
	 */
	public void setHowIijnm(String howIijnm)
	{
		this.howIijnm = howIijnm;
		this.howIijnmModified = true;
	}

	/** 
	 * Sets the value of howIijnmModified
	 */
	public void setHowIijnmModified(boolean howIijnmModified)
	{
		this.howIijnmModified = howIijnmModified;
	}

	/** 
	 * Gets the value of howIijnmModified
	 */
	public boolean isHowIijnmModified()
	{
		return howIijnmModified;
	}

	/**
	 * Method 'getCreatedDate'
	 * 
	 * @return Date
	 */
	public Date getCreatedDate()
	{
		return createdDate;
	}

	/**
	 * Method 'setCreatedDate'
	 * 
	 * @param createdDate
	 */
	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
		this.createdDateModified = true;
	}

	/** 
	 * Sets the value of createdDateModified
	 */
	public void setCreatedDateModified(boolean createdDateModified)
	{
		this.createdDateModified = createdDateModified;
	}

	/** 
	 * Gets the value of createdDateModified
	 */
	public boolean isCreatedDateModified()
	{
		return createdDateModified;
	}

	/**
	 * Method 'getModifiedDate'
	 * 
	 * @return Date
	 */
	public Date getModifiedDate()
	{
		return modifiedDate;
	}

	/**
	 * Method 'setModifiedDate'
	 * 
	 * @param modifiedDate
	 */
	public void setModifiedDate(Date modifiedDate)
	{
		this.modifiedDate = modifiedDate;
		this.modifiedDateModified = true;
	}

	/** 
	 * Sets the value of modifiedDateModified
	 */
	public void setModifiedDateModified(boolean modifiedDateModified)
	{
		this.modifiedDateModified = modifiedDateModified;
	}

	/** 
	 * Gets the value of modifiedDateModified
	 */
	public boolean isModifiedDateModified()
	{
		return modifiedDateModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InterestAttachmentsDetails)) {
			return false;
		}
		
		final InterestAttachmentsDetails _cast = (InterestAttachmentsDetails) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (studentId != _cast.studentId) {
			return false;
		}
		
		if (studentIdNull != _cast.studentIdNull) {
			return false;
		}
		
		if (studentIdModified != _cast.studentIdModified) {
			return false;
		}
		
		if (accomplishments == null ? _cast.accomplishments != accomplishments : !accomplishments.equals( _cast.accomplishments )) {
			return false;
		}
		
		if (accomplishmentsModified != _cast.accomplishmentsModified) {
			return false;
		}
		
		if (specialSkills == null ? _cast.specialSkills != specialSkills : !specialSkills.equals( _cast.specialSkills )) {
			return false;
		}
		
		if (specialSkillsModified != _cast.specialSkillsModified) {
			return false;
		}
		
		if (hobbies == null ? _cast.hobbies != hobbies : !hobbies.equals( _cast.hobbies )) {
			return false;
		}
		
		if (hobbiesModified != _cast.hobbiesModified) {
			return false;
		}
		
		if (otherInterests == null ? _cast.otherInterests != otherInterests : !otherInterests.equals( _cast.otherInterests )) {
			return false;
		}
		
		if (otherInterestsModified != _cast.otherInterestsModified) {
			return false;
		}
		
		if (uploadReference == null ? _cast.uploadReference != uploadReference : !uploadReference.equals( _cast.uploadReference )) {
			return false;
		}
		
		if (uploadReferenceModified != _cast.uploadReferenceModified) {
			return false;
		}
		
		if (academicCertificates == null ? _cast.academicCertificates != academicCertificates : !academicCertificates.equals( _cast.academicCertificates )) {
			return false;
		}
		
		if (academicCertificatesModified != _cast.academicCertificatesModified) {
			return false;
		}
		
		if (supportingDocs == null ? _cast.supportingDocs != supportingDocs : !supportingDocs.equals( _cast.supportingDocs )) {
			return false;
		}
		
		if (supportingDocsModified != _cast.supportingDocsModified) {
			return false;
		}
		
		if (uploadEssay == null ? _cast.uploadEssay != uploadEssay : !uploadEssay.equals( _cast.uploadEssay )) {
			return false;
		}
		
		if (uploadEssayModified != _cast.uploadEssayModified) {
			return false;
		}
		
		if (howIijnm == null ? _cast.howIijnm != howIijnm : !howIijnm.equals( _cast.howIijnm )) {
			return false;
		}
		
		if (howIijnmModified != _cast.howIijnmModified) {
			return false;
		}
		
		if (createdDate == null ? _cast.createdDate != createdDate : !createdDate.equals( _cast.createdDate )) {
			return false;
		}
		
		if (createdDateModified != _cast.createdDateModified) {
			return false;
		}
		
		if (modifiedDate == null ? _cast.modifiedDate != modifiedDate : !modifiedDate.equals( _cast.modifiedDate )) {
			return false;
		}
		
		if (modifiedDateModified != _cast.modifiedDateModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + studentId;
		_hashCode = 29 * _hashCode + (studentIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (studentIdModified ? 1 : 0);
		if (accomplishments != null) {
			_hashCode = 29 * _hashCode + accomplishments.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (accomplishmentsModified ? 1 : 0);
		if (specialSkills != null) {
			_hashCode = 29 * _hashCode + specialSkills.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (specialSkillsModified ? 1 : 0);
		if (hobbies != null) {
			_hashCode = 29 * _hashCode + hobbies.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (hobbiesModified ? 1 : 0);
		if (otherInterests != null) {
			_hashCode = 29 * _hashCode + otherInterests.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (otherInterestsModified ? 1 : 0);
		if (uploadReference != null) {
			_hashCode = 29 * _hashCode + uploadReference.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (uploadReferenceModified ? 1 : 0);
		if (academicCertificates != null) {
			_hashCode = 29 * _hashCode + academicCertificates.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (academicCertificatesModified ? 1 : 0);
		if (supportingDocs != null) {
			_hashCode = 29 * _hashCode + supportingDocs.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (supportingDocsModified ? 1 : 0);
		if (uploadEssay != null) {
			_hashCode = 29 * _hashCode + uploadEssay.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (uploadEssayModified ? 1 : 0);
		if (howIijnm != null) {
			_hashCode = 29 * _hashCode + howIijnm.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (howIijnmModified ? 1 : 0);
		if (createdDate != null) {
			_hashCode = 29 * _hashCode + createdDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (createdDateModified ? 1 : 0);
		if (modifiedDate != null) {
			_hashCode = 29 * _hashCode + modifiedDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (modifiedDateModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InterestAttachmentsDetailsPk
	 */
	public InterestAttachmentsDetailsPk createPk()
	{
		return new InterestAttachmentsDetailsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.edu.iijnm.dto.InterestAttachmentsDetails: " );
		ret.append( "id=" + id );
		ret.append( ", studentId=" + studentId );
		ret.append( ", accomplishments=" + accomplishments );
		ret.append( ", specialSkills=" + specialSkills );
		ret.append( ", hobbies=" + hobbies );
		ret.append( ", otherInterests=" + otherInterests );
		ret.append( ", uploadReference=" + uploadReference );
		ret.append( ", academicCertificates=" + academicCertificates );
		ret.append( ", supportingDocs=" + supportingDocs );
		ret.append( ", uploadEssay=" + uploadEssay );
		ret.append( ", howIijnm=" + howIijnm );
		ret.append( ", createdDate=" + createdDate );
		ret.append( ", modifiedDate=" + modifiedDate );
		return ret.toString();
	}

}
