/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.edu.iijnm.dto;

import com.edu.iijnm.dao.*;
import com.edu.iijnm.factory.*;
import com.edu.iijnm.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class LoginDetails implements Serializable
{
	/** 
	 * This attribute maps to the column id in the login_details table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column login_id in the login_details table.
	 */
	protected int loginId;

	/** 
	 * This attribute represents whether the primitive attribute loginId is null.
	 */
	protected boolean loginIdNull = true;

	/** 
	 * This attribute represents whether the attribute loginId has been modified since being read from the database.
	 */
	protected boolean loginIdModified = false;

	/** 
	 * This attribute maps to the column username in the login_details table.
	 */
	protected String username;

	/** 
	 * This attribute represents whether the attribute username has been modified since being read from the database.
	 */
	protected boolean usernameModified = false;

	/** 
	 * This attribute maps to the column password in the login_details table.
	 */
	protected String password;

	/** 
	 * This attribute represents whether the attribute password has been modified since being read from the database.
	 */
	protected boolean passwordModified = false;

	/** 
	 * This attribute maps to the column created_date in the login_details table.
	 */
	protected Date createdDate;

	/** 
	 * This attribute represents whether the attribute createdDate has been modified since being read from the database.
	 */
	protected boolean createdDateModified = false;

	/** 
	 * This attribute maps to the column modified_date in the login_details table.
	 */
	protected Date modifiedDate;

	/** 
	 * This attribute represents whether the attribute modifiedDate has been modified since being read from the database.
	 */
	protected boolean modifiedDateModified = false;

	/**
	 * Method 'LoginDetails'
	 * 
	 */
	public LoginDetails()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getLoginId'
	 * 
	 * @return int
	 */
	public int getLoginId()
	{
		return loginId;
	}

	/**
	 * Method 'setLoginId'
	 * 
	 * @param loginId
	 */
	public void setLoginId(int loginId)
	{
		this.loginId = loginId;
		this.loginIdNull = false;
		this.loginIdModified = true;
	}

	/**
	 * Method 'setLoginIdNull'
	 * 
	 * @param value
	 */
	public void setLoginIdNull(boolean value)
	{
		this.loginIdNull = value;
		this.loginIdModified = true;
	}

	/**
	 * Method 'isLoginIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isLoginIdNull()
	{
		return loginIdNull;
	}

	/** 
	 * Sets the value of loginIdModified
	 */
	public void setLoginIdModified(boolean loginIdModified)
	{
		this.loginIdModified = loginIdModified;
	}

	/** 
	 * Gets the value of loginIdModified
	 */
	public boolean isLoginIdModified()
	{
		return loginIdModified;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
		this.usernameModified = true;
	}

	/** 
	 * Sets the value of usernameModified
	 */
	public void setUsernameModified(boolean usernameModified)
	{
		this.usernameModified = usernameModified;
	}

	/** 
	 * Gets the value of usernameModified
	 */
	public boolean isUsernameModified()
	{
		return usernameModified;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
		this.passwordModified = true;
	}

	/** 
	 * Sets the value of passwordModified
	 */
	public void setPasswordModified(boolean passwordModified)
	{
		this.passwordModified = passwordModified;
	}

	/** 
	 * Gets the value of passwordModified
	 */
	public boolean isPasswordModified()
	{
		return passwordModified;
	}

	/**
	 * Method 'getCreatedDate'
	 * 
	 * @return Date
	 */
	public Date getCreatedDate()
	{
		return createdDate;
	}

	/**
	 * Method 'setCreatedDate'
	 * 
	 * @param createdDate
	 */
	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
		this.createdDateModified = true;
	}

	/** 
	 * Sets the value of createdDateModified
	 */
	public void setCreatedDateModified(boolean createdDateModified)
	{
		this.createdDateModified = createdDateModified;
	}

	/** 
	 * Gets the value of createdDateModified
	 */
	public boolean isCreatedDateModified()
	{
		return createdDateModified;
	}

	/**
	 * Method 'getModifiedDate'
	 * 
	 * @return Date
	 */
	public Date getModifiedDate()
	{
		return modifiedDate;
	}

	/**
	 * Method 'setModifiedDate'
	 * 
	 * @param modifiedDate
	 */
	public void setModifiedDate(Date modifiedDate)
	{
		this.modifiedDate = modifiedDate;
		this.modifiedDateModified = true;
	}

	/** 
	 * Sets the value of modifiedDateModified
	 */
	public void setModifiedDateModified(boolean modifiedDateModified)
	{
		this.modifiedDateModified = modifiedDateModified;
	}

	/** 
	 * Gets the value of modifiedDateModified
	 */
	public boolean isModifiedDateModified()
	{
		return modifiedDateModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LoginDetails)) {
			return false;
		}
		
		final LoginDetails _cast = (LoginDetails) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (loginId != _cast.loginId) {
			return false;
		}
		
		if (loginIdNull != _cast.loginIdNull) {
			return false;
		}
		
		if (loginIdModified != _cast.loginIdModified) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (usernameModified != _cast.usernameModified) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (passwordModified != _cast.passwordModified) {
			return false;
		}
		
		if (createdDate == null ? _cast.createdDate != createdDate : !createdDate.equals( _cast.createdDate )) {
			return false;
		}
		
		if (createdDateModified != _cast.createdDateModified) {
			return false;
		}
		
		if (modifiedDate == null ? _cast.modifiedDate != modifiedDate : !modifiedDate.equals( _cast.modifiedDate )) {
			return false;
		}
		
		if (modifiedDateModified != _cast.modifiedDateModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + loginId;
		_hashCode = 29 * _hashCode + (loginIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (loginIdModified ? 1 : 0);
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (usernameModified ? 1 : 0);
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (passwordModified ? 1 : 0);
		if (createdDate != null) {
			_hashCode = 29 * _hashCode + createdDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (createdDateModified ? 1 : 0);
		if (modifiedDate != null) {
			_hashCode = 29 * _hashCode + modifiedDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (modifiedDateModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return LoginDetailsPk
	 */
	public LoginDetailsPk createPk()
	{
		return new LoginDetailsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.edu.iijnm.dto.LoginDetails: " );
		ret.append( "id=" + id );
		ret.append( ", loginId=" + loginId );
		ret.append( ", username=" + username );
		ret.append( ", password=" + password );
		ret.append( ", createdDate=" + createdDate );
		ret.append( ", modifiedDate=" + modifiedDate );
		return ret.toString();
	}

}
